---
title: "AoU Trial Eligibility Final"
author: "Cathy Shyr"
date: "2023-06-22"
output: pdf_document
---

```{r, Load packages}
library(bigrquery)
library(plyr)
library(tidyverse)
library(data.table)
library(httr)
library(jsonlite)
library(tidyr)
library(stringr)
library(plotly)
library(MASS)
library(foreach)
library(doParallel)
library(dplyr)
library(parallel)
library(PheWAS)
library(ggridges)
library(ggdist)
library(DescTools)
library(forcats)
```

```{r}
# the current workspace's dataset variable (to use in the query)
dataset = Sys.getenv('WORKSPACE_CDR')

# helper function to make the download easier
download_data <- function(query) {
   tb <- bq_project_query(Sys.getenv('GOOGLE_PROJECT'), query)
   bq_table_download(tb)
}
```

```{r}
# Extract observations that have at least 2 entries of a given EHR condition
person_condition_query <- str_glue("SELECT 
                                        person.person_id,
                                        person.sex_at_birth_concept_id, 
                                        person.birth_datetime as date_of_birth,
                                        person.race_concept_id,
                                        person.ethnicity_concept_id,
                                        condition_occurrence.condition_concept_id,
                                        condition_occurrence.condition_source_value,
                                        observation.value_as_string,
                                        concept.concept_code,
                                        concept.concept_name
                                    FROM
                                        `{dataset}.person` person
                                    JOIN
                                        `{dataset}.condition_occurrence` condition_occurrence
                                    ON 
                                        person.person_id = condition_occurrence.person_id
                                    JOIN
                                        `{dataset}.concept` concept
                                    ON
                                        condition_occurrence.condition_concept_id = concept.concept_id
                                    LEFT JOIN
                                        `{dataset}.observation` observation
                                    ON
                                        person.person_id = observation.person_id
                                    WHERE
                                        observation.observation_source_concept_id = 1585250
                                    QUALIFY ROW_NUMBER() OVER(PARTITION BY condition_occurrence.person_id, condition_occurrence.condition_concept_id
                                                              ORDER     BY condition_occurrence.condition_concept_id) = 2")

person_condition_df <- download_data(person_condition_query)
person_condition_df$age_in_years <- (as.Date("2023-02-14")-as.Date(person_condition_df$date_of_birth))/365
person_condition_df$age_in_years <- as.numeric(gsub(" days", "", person_condition_df$age_in_years))
person_condition_df <- as.data.table(person_condition_df)
write.csv(person_condition_df, file = "person_condition_df.csv")

# sex_at_birth_concept_id
# 45878463 - Female
# 45880669 - Male
# 1177221 - Prefer not to answer
# 46273637 - Intersex
# 4124462 - None

# race_concept_id
# 38003615 - Middle Eastern or North African
# 8557 - Native Hawaiian or Other Pacific Islander
# 2100000001 - None indicated
# 2000000008 - Multiple selections of above; 
# 8515 - Asian
# 8516 - Black or African American
# 8527 - White
# 1177221 - Prefer not to answer
# 903096 - Skip; 
# 45882607 - None of these

# ethnicity_concept_id
# 38003564 - Not Hispanic or Latino
# 38003563 - Hispanic or Latino
# 903079 - Prefer not to answer
# 903096 - Skip
# 1586148 - None of these
```

```{r}
########################################################################################
#                                                                                      #
#                                     Map to PheCodes                                  #        
#                                                                                      #
########################################################################################
person_condition_df <- fread("person_condition_df.csv", header = TRUE)

# Read in PheCode files
phecode_icd9 <- as.data.table(fread("phecode_icd9_rolled.csv", header = TRUE))
phecode_icd10 <- as.data.table(fread("phecode_icd10.csv", header = TRUE))
phecode_icd10cm <- as.data.table(fread("Phecode_map_v1_2_icd10cm_beta.csv", header = TRUE))
names(phecode_icd9) <- c("condition_source_value", names(phecode_icd9)[-1])
names(phecode_icd10) <- c("condition_source_value", names(phecode_icd10)[-1])
names(phecode_icd10cm) <- c("condition_source_value", "icd10cm_str", "PheCode", "Phenotype", "exclude_range", "exclude_name", "leaf", "rollup")

Phecode_Phenotype <- rbind(phecode_icd9[, c("condition_source_value", "PheCode", "Phenotype")],
                     phecode_icd10[, c("condition_source_value", "PheCode", "Phenotype")],
                     phecode_icd10cm[, c("condition_source_value", "PheCode", "Phenotype")])
Phecode_Phenotype <- Phecode_Phenotype %>% distinct()
# There are a few where the Phecode exists but the phenotype is empty, so remove those
Phecode_Phenotype <- Phecode_Phenotype[-which(Phecode_Phenotype$Phenotype %in% ""), ]

Phecode_Map <- rbind(Phecode_Phenotype[, c("condition_source_value", "PheCode")],
                     Phecode_Phenotype[, c("condition_source_value", "PheCode")],
                     Phecode_Phenotype[, c("condition_source_value", "PheCode")])
Phecode_Map <- Phecode_Map %>% distinct()

# Map source concept code to PheCode (direct mapping)
person_condition_df_phecode <- Phecode_Map[person_condition_df, on = "condition_source_value", allow.cartesian = TRUE]
person_condition_df_phecode_final <- person_condition_df_phecode %>% distinct()
# The code below handles cases where non-ICD vocab concepts are mapped to the same OMOP
# concept as the ICD concept in the data. However, because these are non-ICD vocabs,
# they were not mapped to Phecodes in the first step. So I will merge on the concept_name
# in order to map these non-ICD vocabs to Phecodes
person_condition_df_phecode_final_name_PheCode <- person_condition_df_phecode_final[, c("concept_name", "PheCode")]
person_condition_df_phecode_final_name_PheCode <- person_condition_df_phecode_final_name_PheCode %>% distinct()
person_condition_df_phecode_final_name_PheCode <- person_condition_df_phecode_final_name_PheCode[which(!is.na(person_condition_df_phecode_final_name_PheCode$PheCode)), ]
names(person_condition_df_phecode_final_name_PheCode) <- c("concept_name", "PheCode2")
person_condition_df_phecode_final2 <- person_condition_df_phecode_final_name_PheCode[person_condition_df_phecode_final, on = "concept_name", allow.cartesian = TRUE]
person_condition_df_phecode_final2[which(is.na(person_condition_df_phecode_final2$PheCode))]$PheCode <- person_condition_df_phecode_final2[which(is.na(person_condition_df_phecode_final2$PheCode))]$PheCode2
person_condition_df_phecode_final <- person_condition_df_phecode_final2[, -c("PheCode2")]
# paste("Total number of non-directly mappable conditions =", length(unique(person_condition_df_phecode_final[which(is.na(person_condition_df_phecode_final$PheCode))]$condition_source_value)))
# paste("Total number of unique source conditions =", length(unique(person_condition_df_phecode_final$condition_source_value)))

# Concept_ids to map to ICD (indirect mapping)
need2Map <- unique(person_condition_df_phecode_final[which(is.na(person_condition_df_phecode_final$PheCode)), ]$condition_concept_id)
# Number of codes that are not ICD
# length(need2Map)
need2Map_collapse <- paste0(need2Map, collapse = ',')

# Obtain all of these codes where relationship_id = "Mapped from"
concept_id_Mapped_from_query <- str_glue("SELECT 
                                           concept_relationship.concept_id_1,
                                           concept_relationship.concept_id_2
                                        FROM
                                           `{dataset}.concept_relationship` concept_relationship
                                        WHERE
                                           concept_relationship.concept_id_1 IN ({need2Map_collapse})
                                        AND
                                           concept_relationship.relationship_id = 'Mapped from'")
concept_id_Mapped_from_dat <- as.data.table(download_data(concept_id_Mapped_from_query))

# Retain the ones that were mapped from ICD9-CM or ICD10-CM
# Need to break up into 2 parts because string is too long otherwise
concept_id_Mapped_from_dat_id_part1 <- paste0(concept_id_Mapped_from_dat$concept_id_2[1:floor(nrow(concept_id_Mapped_from_dat)/2)], collapse = ',')
concept_id_Mapped_from_dat_id_part2 <- paste0(concept_id_Mapped_from_dat$concept_id_2[(floor(nrow(concept_id_Mapped_from_dat)/2) + 1):nrow(concept_id_Mapped_from_dat)], collapse = ',')
concept_id2_vocab_query_part1 <- str_glue("SELECT 
                                        concept.concept_id,
                                        concept.vocabulary_id,
                                        concept.concept_code
                                     FROM
                                        `{dataset}.concept` concept
                                     WHERE
                                        concept.concept_id IN ({concept_id_Mapped_from_dat_id_part1})")
concept_id2_vocab_query_part2 <- str_glue("SELECT 
                                        concept.concept_id,
                                        concept.vocabulary_id,
                                        concept.concept_code
                                     FROM
                                        `{dataset}.concept` concept
                                     WHERE
                                        concept.concept_id IN ({concept_id_Mapped_from_dat_id_part2})")
concept_id2_vocab_dat_part1 <- as.data.table(download_data(concept_id2_vocab_query_part1))
concept_id2_vocab_dat_part2 <- as.data.table(download_data(concept_id2_vocab_query_part2))
concept_id2_vocab_dat <- rbind(concept_id2_vocab_dat_part1, concept_id2_vocab_dat_part2)
names(concept_id2_vocab_dat) <- c("concept_id_2", "vocabulary_id", "concept_code")
concept_id_Mapped_from_dat_vocab <- concept_id2_vocab_dat[concept_id_Mapped_from_dat, on = "concept_id_2"]
concept_id_Mapped_from_dat_vocab_ICD <- concept_id_Mapped_from_dat_vocab[which(concept_id_Mapped_from_dat_vocab$vocabulary_id %in% c("ICD9CM", "ICD10CM")), ]
# Map to PheCodes
names(Phecode_Map) <- c("concept_code", "PheCode")
concept_id_Mapped_from_dat_vocab_ICD_phecode <- Phecode_Map[concept_id_Mapped_from_dat_vocab_ICD, on = "concept_code"]


concept_id_Mapped_from_dat_vocab_ICD_phecode <- concept_id_Mapped_from_dat_vocab_ICD_phecode[-which(is.na(concept_id_Mapped_from_dat_vocab_ICD_phecode$PheCode)), ]
need2Map_PheCode <- concept_id_Mapped_from_dat_vocab_ICD_phecode[, c("concept_id_1", "PheCode")]
need2Map_PheCode <- need2Map_PheCode %>% distinct()
names(need2Map_PheCode) <- c("condition_concept_id", "PheCode_indirect")
person_condition_df_phecode_final_final <- need2Map_PheCode[person_condition_df_phecode_final, on = "condition_concept_id", allow.cartesian = TRUE]

# Reconcile extraneous cases
person_condition_df_phecode_final_final_name_PheCode <- person_condition_df_phecode_final_final[, c("concept_name", "PheCode_indirect")]
person_condition_df_phecode_final_final_name_PheCode <- person_condition_df_phecode_final_final_name_PheCode %>% distinct()
person_condition_df_phecode_final_final_name_PheCode <- person_condition_df_phecode_final_final_name_PheCode[which(!is.na(person_condition_df_phecode_final_final_name_PheCode$PheCode_indirect)), ]
names(person_condition_df_phecode_final_final_name_PheCode) <- c("concept_name", "PheCode2")
person_condition_df_phecode_final_final2 <- person_condition_df_phecode_final_final_name_PheCode[person_condition_df_phecode_final_final, on = "concept_name", allow.cartesian = TRUE]
person_condition_df_phecode_final_final2[which(is.na(person_condition_df_phecode_final_final2$PheCode_indirect))]$PheCode_indirect <- person_condition_df_phecode_final_final2[which(is.na(person_condition_df_phecode_final_final2$PheCode_indirect))]$PheCode2
person_condition_df_phecode_final_final <- person_condition_df_phecode_final_final2[, -c("PheCode2")]

# If PheCode is there, default to PheCode, if not, default to PheCode_indirect, if not, default to original concept_code
person_condition_df_phecode_final_final$Mappable <- "Yes"
person_condition_df_phecode_final_final$PheCode[which(is.na(person_condition_df_phecode_final_final$PheCode))] <- person_condition_df_phecode_final_final$PheCode_indirect[which(is.na(person_condition_df_phecode_final_final$PheCode))]
# paste("Total number of non-mappable conditions =", length(unique(person_condition_df_phecode_final_final[which(is.na(person_condition_df_phecode_final_final$PheCode))]$condition_source_value)))
# Set those that were not mappable to Phecodes to "No" for "Mappable" column
person_condition_df_phecode_final_final$Mappable[which(is.na(person_condition_df_phecode_final_final$PheCode))] <- "No"

# Add Phenotype to the tables
Phecode_Phenotype <- rbind(phecode_icd9[, c("PheCode", "Phenotype")],
                     phecode_icd10[, c("PheCode", "Phenotype")],
                     phecode_icd10cm[, c("PheCode", "Phenotype")])
Phecode_Phenotype <- Phecode_Phenotype %>% distinct()
Phecode_Phenotype <- Phecode_Phenotype[-which(Phecode_Phenotype$Phenotype %in% ""), ]
# Merge by PheCode
person_condition_df_phecode_phenotype <- Phecode_Phenotype[person_condition_df_phecode_final_final, on = "PheCode", allow.cartesian = TRUE]
person_condition_df_phecode_phenotype$Phenotype[which(is.na(person_condition_df_phecode_phenotype$PheCode))] <- person_condition_df_phecode_phenotype$concept_name[which(is.na(person_condition_df_phecode_phenotype$PheCode))]
person_condition_df_phecode_phenotype$PheCode[which(is.na(person_condition_df_phecode_phenotype$PheCode))] <- person_condition_df_phecode_phenotype$concept_code[which(is.na(person_condition_df_phecode_phenotype$PheCode))]
person_condition_df_phecode_phenotype <- person_condition_df_phecode_phenotype[, -c("PheCode_indirect")]

# AoU coverage check
AoU_coverage_check <- person_condition_df_phecode_phenotype[, c("person_id", "concept_code", "Mappable")]
AoU_coverage_check <- AoU_coverage_check %>% distinct()
# paste0("Phecode coverage across AoU conditions =", length(which(AoU_coverage_check$Mappable %in% "Yes"))/nrow(AoU_coverage_check))

# Just keep the ones that are mappable to Phecodes
person_condition_df_phecode_phenotype <- person_condition_df_phecode_phenotype[which(person_condition_df_phecode_phenotype$Mappable %in% "Yes"), ]
person_condition_df_phecode_phenotype <- person_condition_df_phecode_phenotype %>% distinct()
write.csv(person_condition_df_phecode_phenotype, file = "person_condition_df_phecode_phenotype.csv")
```

```{r}
##############################################################################################
#                                  CTgov API Loop                                            #
##############################################################################################
# Obtain a list of unique AoU conditions
person_condition_df_phecode_phenotype <- person_condition_df_phecode_phenotype[which(person_condition_df_phecode_phenotype$Mappable %in% "Yes"), ]
concept_dat <- person_condition_df_phecode_phenotype[, c("PheCode", "Phenotype")] %>% distinct()
names(concept_dat) <- c("concept_code", "concept_name")
concept_dat$concept_name <- tolower(concept_dat$concept_name)
concept_dat$concept_name_url <- sapply(concept_dat$concept_name, URLencode, USE.NAMES = FALSE)

API_result_list <- vector("list", length = nrow(concept_dat))

# Query each phenotype on CTgov and save the result
for(x in 1:nrow(concept_dat)){
  print(x)
  query_url <- paste0("https://www.clinicaltrials.gov/api/query/study_fields?expr=COVERAGE%5BContains%5D", concept_dat$concept_name_url[x], "+AND+EXPANSION%5BRelaxation%5D", concept_dat$concept_name_url[x], "+AND+SEARCH%5BLocation%5D%28AREA%5BLocationCountry%5DUnited+States+AND+AREA%5BLocationStatus%5DRecruiting%29+&fields=NCTId%2CGender%2CMinimumAge%2CMaximumAge%2CLocationZip%2CLeadSponsorClass%2CLeadSponsorName%2CCollaboratorName%2CCollaboratorClass%2CStudyType&min_rnk=1&max_rnk=1000&fmt=json")
  search_result <- httr::GET(query_url, config = httr::config(connecttimeout = 60))
  parsed_result <- fromJSON(rawToChar(search_result$content))
  numStudy <- parsed_result$StudyFieldsResponse$NStudiesFound
  if(is.null(numStudy)){
    API_result_list[[x]] <- data.frame(Index = NA, NCTId = NA, Gender = NA, MinimumAge = NA, MaximumAge = NA, Zip = NA, LeadSponsorClass = NA, LeadSponsorName = NA, CollaboratorName = NA, CollaboratorClass = NA, StudyType = NA, concept_code = concept_dat$concept_code[x])
  }else{
    if(numStudy == 0){
      API_result_list[[x]] <- data.frame(Index = NA, NCTId = NA, Gender = NA, MinimumAge = NA, MaximumAge = NA, Zip = NA, LeadSponsorClass = NA, LeadSponsorName = NA, CollaboratorName = NA, CollaboratorClass = NA, StudyType = NA, concept_code = concept_dat$concept_code[x])
    }else{
      API_result_list[[x]] <- parsed_result$StudyFieldsResponse$StudyFields
      names(API_result_list[[x]]) <- c("Index", "NCTId", "Gender", "MinimumAge", "MaximumAge", "Zip", "LeadSponsorClass", "LeadSponsorName", "CollaboratorName", "CollaboratorClass", "StudyType")
      API_result_list[[x]]$concept_code <- concept_dat$concept_code[x]
    }
    # Search up to 5000 records if needed
    if(numStudy > 1000){
      query_url <- paste0("https://www.clinicaltrials.gov/api/query/study_fields?expr=COVERAGE%5BContains%5D", concept_dat$concept_name_url[x], "+AND+EXPANSION%5BRelaxation%5D", concept_dat$concept_name_url[x], "+AND+SEARCH%5BLocation%5D%28AREA%5BLocationCountry%5DUnited+States+AND+AREA%5BLocationStatus%5DRecruiting%29+&fields=NCTId%2CGender%2CMinimumAge%2CMaximumAge%2CLocationZip%2CLeadSponsorClass%2CLeadSponsorName%2CCollaboratorName%2CCollaboratorClass%2CStudyType&min_rnk=1001&max_rnk=2000&fmt=json")
      search_result <- httr::GET(query_url, config = httr::config(connecttimeout = 60))
      parsed_result <- fromJSON(rawToChar(search_result$content))
      tmp <- parsed_result$StudyFieldsResponse$StudyFields
      tmp$concept_code <- concept_dat$concept_code[x]
      names(tmp) <- colnames(API_result_list[[x]])
      API_result_list[[x]] <- rbind(API_result_list[[x]], tmp)
      if(numStudy > 2000){
        query_url <- paste0("https://www.clinicaltrials.gov/api/query/study_fields?expr=COVERAGE%5BContains%5D", concept_dat$concept_name_url[x], "+AND+EXPANSION%5BRelaxation%5D", concept_dat$concept_name_url[x], "+AND+SEARCH%5BLocation%5D%28AREA%5BLocationCountry%5DUnited+States+AND+AREA%5BLocationStatus%5DRecruiting%29+&fields=NCTId%2CGender%2CMinimumAge%2CMaximumAge%2CLocationZip%2CLeadSponsorClass%2CLeadSponsorName%2CCollaboratorName%2CCollaboratorClass%2CStudyType&min_rnk=2001&max_rnk=3000&fmt=json")
        search_result <- httr::GET(query_url, config = httr::config(connecttimeout = 60))
        parsed_result <- fromJSON(rawToChar(search_result$content))
        tmp <- parsed_result$StudyFieldsResponse$StudyFields
        tmp$concept_code <- concept_dat$concept_code[x]
        names(tmp) <- colnames(API_result_list[[x]])
        API_result_list[[x]] <- rbind(API_result_list[[x]], tmp)
        if(numStudy > 3000){
          query_url <- paste0("https://www.clinicaltrials.gov/api/query/study_fields?expr=COVERAGE%5BContains%5D", concept_dat$concept_name_url[x], "+AND+EXPANSION%5BRelaxation%5D", concept_dat$concept_name_url[x], "+AND+SEARCH%5BLocation%5D%28AREA%5BLocationCountry%5DUnited+States+AND+AREA%5BLocationStatus%5DRecruiting%29+&fields=NCTId%2CGender%2CMinimumAge%2CMaximumAge%2CLocationZip%2CLeadSponsorClass%2CLeadSponsorName%2CCollaboratorName%2CCollaboratorClass%2CStudyType&min_rnk=3001&max_rnk=4000&fmt=json")
          search_result <- httr::GET(query_url, config = httr::config(connecttimeout = 60))
          parsed_result <- fromJSON(rawToChar(search_result$content))
          tmp <- parsed_result$StudyFieldsResponse$StudyFields
          tmp$concept_code <- concept_dat$concept_code[x]
          names(tmp) <- colnames(API_result_list[[x]])
          API_result_list[[x]] <- rbind(API_result_list[[x]], tmp)
          if(numStudy > 4000){
            query_url <- paste0("https://www.clinicaltrials.gov/api/query/study_fields?expr=COVERAGE%5BContains%5D", concept_dat$concept_name_url[x], "+AND+EXPANSION%5BRelaxation%5D", concept_dat$concept_name_url[x], "+AND+SEARCH%5BLocation%5D%28AREA%5BLocationCountry%5DUnited+States+AND+AREA%5BLocationStatus%5DRecruiting%29+&fields=NCTId%2CGender%2CMinimumAge%2CMaximumAge%2CLocationZip%2CLeadSponsorClass%2CLeadSponsorName%2CCollaboratorName%2CCollaboratorClass%2CStudyType&min_rnk=4001&max_rnk=5000&fmt=json")
            search_result <- httr::GET(query_url, config = httr::config(connecttimeout = 60))
            parsed_result <- fromJSON(rawToChar(search_result$content))
            tmp <- parsed_result$StudyFieldsResponse$StudyFields
            tmp$concept_code <- concept_dat$concept_code[x]
            names(tmp) <- colnames(API_result_list[[x]])
            API_result_list[[x]] <- rbind(API_result_list[[x]], tmp)
          }
        }
      }
    }
  }
  API_result <- API_result_list[[x]]
  save(API_result, file = paste0("API_result", x, ".RDa"))
}

API_result_dat <- data.frame(NCTId = c(), Gender = c(), MinimumAge = c(), MaximumAge = c(), Zip = c(), LeadSponsorClass = c(), LeadSponsorName = c(), CollaboratorName = c(), CollaboratorClass = c(), StudyType = c(), concept_code = c())
for(i in 1:nrow(concept_dat)){
  print(i)
  load(paste0("API_result", i, ".RDa"))
  API_result_dat <- rbind(API_result_dat, API_result[, -1])
}
trial_dat <- apply(API_result_dat, 2, as.character)

# Aside
trial_dat <- fread("API_result_dat_phecode.csv", header = TRUE)
names(trial_dat)[which(names(trial_dat) %in% "concept_code")] <- "Phecode"
# write.csv(trial_dat, file = "trial_dat.csv")

##############################################################################################
#                                    Post-processing                                         #
##############################################################################################
# trial_dat <- fread("trial_dat.csv", header = TRUE)
# Convert age to years
minutes_min_ind <- grep("Minutes", trial_dat$MinimumAge)
minutes_min_ind <- c(minutes_min_ind, grep("Minute", trial_dat$MinimumAge))

hours_min_ind <- grep("Hours", trial_dat$MinimumAge)
hours_min_ind <- c(hours_min_ind, grep("Hour", trial_dat$MinimumAge))

days_min_ind <- grep("Days", trial_dat$MinimumAge)
days_min_ind <- c(days_min_ind, grep("Day", trial_dat$MinimumAge))

weeks_min_ind <- grep("Weeks", trial_dat$MinimumAge)
weeks_min_ind <- c(weeks_min_ind, grep("Week", trial_dat$MinimumAge))

months_min_ind <- grep("Months", trial_dat$MinimumAge)
months_min_ind <- c(months_min_ind, grep("Month", trial_dat$MinimumAge))

years_min_ind <- grep("Years", trial_dat$MinimumAge)
years_min_ind <- c(years_min_ind, grep("Year", trial_dat$MinimumAge))

NA_min_ind <- which(is.na(trial_dat$MinimumAge))
NA_min_ind <- c(NA_min_ind, grep("N/A", trial_dat$MinimumAge))
NA_min_ind <- c(NA_min_ind, grep("NA", trial_dat$MinimumAge))
character0_min_ind <- which(trial_dat$MinimumAge %in% "character(0)")
list_min_ind <- which(trial_dat$MinimumAge %in% "list()")

minutes_max_ind <- grep("Minutes", trial_dat$MaximumAge)
minutes_max_ind <- c(minutes_max_ind, grep("Minute", trial_dat$MaximumAge))

hours_max_ind <- grep("Hours", trial_dat$MaximumAge)
hours_max_ind <- c(hours_max_ind, grep("Hour", trial_dat$MaximumAge))

days_max_ind <- grep("Days", trial_dat$MaximumAge)
days_max_ind <- c(days_max_ind, grep("Day", trial_dat$MaximumAge))

weeks_max_ind <- grep("Weeks", trial_dat$MaximumAge)
weeks_max_ind <- c(weeks_max_ind, grep("Week", trial_dat$MaximumAge))

months_max_ind <- grep("Months", trial_dat$MaximumAge)
months_max_ind <- c(months_max_ind, grep("Month", trial_dat$MaximumAge))

years_max_ind <- grep("Years", trial_dat$MaximumAge)
years_max_ind <- c(years_max_ind, grep("Year", trial_dat$MaximumAge))

NA_max_ind <- which(is.na(trial_dat$MaximumAge))
NA_max_ind <- c(NA_max_ind, grep("N/A", trial_dat$MaximumAge))
NA_max_ind <- c(NA_max_ind, grep("NA", trial_dat$MaximumAge))
character0_max_ind <- which(trial_dat$MaximumAge %in% "character(0)")
list_max_ind <- which(trial_dat$MaximumAge %in% "list()")
regexp <- "[[:digit:]]+"

trial_dat$MinimumAge[minutes_min_ind] <- as.numeric(str_extract(trial_dat$MinimumAge[minutes_min_ind], regexp))/(365 * 24 * 60)
trial_dat$MaximumAge[minutes_max_ind] <- as.numeric(str_extract(trial_dat$MaximumAge[minutes_max_ind], regexp))/(365 * 24 * 60)

trial_dat$MinimumAge[hours_min_ind] <- as.numeric(str_extract(trial_dat$MinimumAge[hours_min_ind], regexp))/(365 * 24)
trial_dat$MaximumAge[hours_max_ind] <- as.numeric(str_extract(trial_dat$MaximumAge[hours_max_ind], regexp))/(365 * 24)

trial_dat$MinimumAge[days_min_ind] <- as.numeric(str_extract(trial_dat$MinimumAge[days_min_ind], regexp))/365
trial_dat$MaximumAge[days_max_ind] <- as.numeric(str_extract(trial_dat$MaximumAge[days_max_ind], regexp))/365

trial_dat$MinimumAge[weeks_min_ind] <- as.numeric(str_extract(trial_dat$MinimumAge[weeks_min_ind], regexp))/52
trial_dat$MaximumAge[weeks_max_ind] <- as.numeric(str_extract(trial_dat$MaximumAge[weeks_max_ind], regexp))/52

trial_dat$MinimumAge[months_min_ind] <- as.numeric(str_extract(trial_dat$MinimumAge[months_min_ind], regexp))/12
trial_dat$MaximumAge[months_max_ind] <- as.numeric(str_extract(trial_dat$MaximumAge[months_max_ind], regexp))/12

trial_dat$MinimumAge[years_min_ind] <- as.numeric(str_extract(trial_dat$MinimumAge[years_min_ind], regexp))
trial_dat$MaximumAge[years_max_ind] <- as.numeric(str_extract(trial_dat$MaximumAge[years_max_ind], regexp))

trial_dat$MinimumAge[NA_min_ind] <- 0
trial_dat$MaximumAge[NA_max_ind] <- 100
trial_dat$MinimumAge[character0_min_ind] <- 0
trial_dat$MaximumAge[character0_max_ind] <- 100
trial_dat$MinimumAge[list_min_ind] <- 0
trial_dat$MaximumAge[list_max_ind] <- 100

trial_dat$MinimumAge <- as.numeric(trial_dat$MinimumAge)
trial_dat$MaximumAge <- as.numeric(trial_dat$MaximumAge)

# Exclude pediatric trials/studies
trial_dat <- trial_dat %>% dplyr::filter(MinimumAge >= 18)
write.csv(trial_dat, file = "trial_dat.csv")

###################################
#     Expand on gender and zip    #
###################################
trial_dat <- fread("trial_dat.csv", header = TRUE)
if(length(which(is.na(trial_dat$NCTId))) >= 1){
  trial_dat <- trial_dat[-which(is.na(trial_dat$NCTId)), ]
}
trial_dat <- trial_dat[, c("NCTId", "Gender", "MinimumAge", "MaximumAge", "Zip", "Phecode", "StudyType")]

# Expand based on zip
trial_dat_expanded_zip <- trial_dat %>% 
  mutate(
    Zip = str_replace(Zip, '",', '";'),
    Zip = str_replace_all(Zip, '^c|(?![.,; ])\\W', '')) %>%
  separate_rows(Zip, sep = '; ') %>% separate_rows(Zip, sep = ", ") %>% distinct()

# Restrict to centers that have valid 5-digit zipcode
# Pad the 4 digit zip codes with a leading 0 (R has a tendency to remove the first 0)
trial_dat_expanded_zip$Zip <- str_pad(trial_dat_expanded_zip$Zip, 5, pad = "0")
trial_dat_expanded_zip$Zip <- str_extract(trial_dat_expanded_zip$Zip, "\\b\\d{5}\\b")
trial_dat_expanded_zip <- trial_dat_expanded_zip[grepl("^\\d{5}", trial_dat_expanded_zip$Zip), ]

# Restrict to first 3 digits of zip code
trial_dat_expanded_zip$Zip <- substr(trial_dat_expanded_zip$Zip, 1, 3)
trial_dat_expanded_zip <- trial_dat_expanded_zip %>% distinct()

# Expand based on gender
trial_dat_expanded_zip$Gender <- ifelse(trial_dat_expanded_zip$Gender %in% "Female", "45878463",
                                        ifelse(trial_dat_expanded_zip$Gender %in% "Male", "45880669",
                                               ifelse(trial_dat_expanded_zip$Gender %in% "All",
                                                      "45878463,45880669,9999999999", NA)))
trial_dat_expanded_zip <- trial_dat_expanded_zip %>% tidyr::separate_rows(Gender)
write.csv(trial_dat_expanded_zip, file = "trial_dat_expanded_zip.csv")

##############################################################
#           Create an expanded file without zip              #
##############################################################
trial_dat_expanded <- trial_dat_expanded_zip[, -which(names(trial_dat_expanded_zip) %in% "Zip")]
trial_dat_expanded <- trial_dat_expanded %>% distinct()
write.csv(trial_dat_expanded, file = "trial_dat_expanded.csv")

##############################################################
#           Obtain sponsored studies' NCTIds                 #
##############################################################
trial_dat <- fread("trial_dat.csv", header = TRUE)
if(length(which(is.na(trial_dat$NCTId))) >= 1){
  trial_dat <- trial_dat[-which(is.na(trial_dat$NCTId)), ]
}
trial_dat <- trial_dat[, c("NCTId", "LeadSponsorClass")]

trial_dat_expanded <- trial_dat
NIH_NCTId <- unique(trial_dat_expanded$NCTId[which(trial_dat_expanded$LeadSponsorClass %in% c("NIH"))])
IND_NCTId <- unique(trial_dat_expanded$NCTId[which(trial_dat_expanded$LeadSponsorClass %in% c("INDUSTRY"))])
OTH_NCTId <- unique(trial_dat_expanded$NCTId[which(trial_dat_expanded$LeadSponsorClass %in% c("OTHER"))])

##############################################################
#        Subset expanded datasets to NIH studies             #
##############################################################
trial_dat_expanded <- fread("trial_dat_expanded.csv", header = TRUE)
trial_dat_expanded_zip <- fread("trial_dat_expanded_zip.csv", header = TRUE)
trial_dat_expanded_NIH <- trial_dat_expanded[which(trial_dat_expanded$NCTId %in% NIH_NCTId), ]
trial_dat_expanded_zip_NIH <- trial_dat_expanded_zip[which(trial_dat_expanded_zip$NCTId %in% NIH_NCTId), ]
write.csv(trial_dat_expanded_NIH, file = "trial_dat_expanded_NIH.csv")
write.csv(trial_dat_expanded_zip_NIH, file = "trial_dat_expanded_zip_NIH.csv")

##############################################################
#        Subset expanded datasets to industry studies        #
##############################################################
trial_dat_expanded_IND <- trial_dat_expanded[which(trial_dat_expanded$NCTId %in% IND_NCTId), ]
trial_dat_expanded_zip_IND <- trial_dat_expanded_zip[which(trial_dat_expanded_zip$NCTId %in% IND_NCTId), ]
write.csv(trial_dat_expanded_IND, file = "trial_dat_expanded_IND.csv")
write.csv(trial_dat_expanded_zip_IND, file = "trial_dat_expanded_zip_IND.csv")


##############################################################
#        Subset expanded datasets to academic studies        #
##############################################################
trial_dat_expanded_OTH <- trial_dat_expanded[which(trial_dat_expanded$NCTId %in% OTH_NCTId), ]
trial_dat_expanded_zip_OTH <- trial_dat_expanded_zip[which(trial_dat_expanded_zip$NCTId %in% OTH_NCTId), ]
write.csv(trial_dat_expanded_OTH, file = "trial_dat_expanded_OTH.csv")
write.csv(trial_dat_expanded_zip_OTH, file = "trial_dat_expanded_zip_OTH.csv")

```

```{r, Match Participants with Trials}
####################################################################################################
#                              Match Based on Age and Sex For Trials Only                          #
####################################################################################################
##############################################################################################
#                                     Read in Data                                           #
##############################################################################################
# AoU data
person_condition_df_phecode_phenotype <- as.data.table(fread("person_condition_df_phecode_phenotype.csv", header = TRUE))
person_condition_df_phecode_phenotype <- person_condition_df_phecode_phenotype[, c("person_id", "sex_at_birth_concept_id", "age_in_years", "PheCode")]
names(person_condition_df_phecode_phenotype) <- c("person_id", "sex_at_birth_concept_id", "age_in_years", "Phecode")

# Code sex as male, female, or other to match with CTgov 
person_condition_df_phecode_phenotype$sex_at_birth_concept_id[which(!(person_condition_df_phecode_phenotype$sex_at_birth_concept_id %in% c(45880669, 45878463)))] <- 9999999999
# alloc.col(person_condition_df)

# CTgov data
# Even though this is matching without zip, just use the set where trials have at least 1 valid U.S.-based location
trial_dat_expanded <- as.data.table(fread("trial_dat_expanded.csv", header = TRUE))
trial_dat_expanded <- trial_dat_expanded[, -1]
trial_dat_expanded <- trial_dat_expanded[which(trial_dat_expanded$StudyType %in% "Interventional"), ]
trial_dat_expanded <- trial_dat_expanded[, c("StudyType"):= NULL]
trial_dat_expanded$MinimumAge <- as.double(trial_dat_expanded$MinimumAge)
trial_dat_expanded$Gender <- as.double(trial_dat_expanded$Gender)
names(trial_dat_expanded) <- c("NCTId", "sex_at_birth_concept_id", "MinimumAge", "MaximumAge", "Phecode")


####################################################################################################
#                              Match Based on Age and Sex                                          #
####################################################################################################
# For each participant, count the number of studies s/he is eligible for
AoU_to_CTgov_Trial <- trial_dat_expanded[person_condition_df_phecode_phenotype, on = c("Phecode", "sex_at_birth_concept_id", "MaximumAge >= age_in_years", "MinimumAge <= age_in_years"), .(list(NCTId)), by = .EACHI]
AoU_to_CTgov_Trial$person_id <- person_condition_df_phecode_phenotype$person_id
AoU_to_CTgov_Trial_ReturnOfValue <- AoU_to_CTgov_Trial
AoU_to_CTgov_Trial_ReturnOfValue <- AoU_to_CTgov_Trial_ReturnOfValue[, c("person_id", "V1", "Phecode")]
AoU_to_CTgov_Trial <- AoU_to_CTgov_Trial[, .(nMatch = uniqueN(unlist(V1), na.rm = TRUE)), by = .(person_id)]
write.csv(AoU_to_CTgov_Trial, file = "AoU_to_CTgov_Trial.csv")
AoU_to_CTgov_Trial <- AoU_to_CTgov_Trial[order(AoU_to_CTgov_Trial$nMatch, decreasing = TRUE), ]
# barplot(AoU_to_CTgov_Trial$nMatch, xlab = "Participant", ylab = "Number of Eligible Trials", main = "Number of Eligible Trials by Participant", ylim = c(0, 20000))
AoU_to_CTgov_Trial$category <- ifelse(AoU_to_CTgov_Trial$nMatch == 0, 0, 
                                         ifelse(AoU_to_CTgov_Trial$nMatch <= 500, 1, 
                                                ifelse(AoU_to_CTgov_Trial$nMatch <= 1000, 2, 3)))

# table(AoU_to_CTgov_Trial$category)

# For each trial, count the number of eligible participants
CTgov_to_AoU_Trial <- person_condition_df_phecode_phenotype[trial_dat_expanded, on = c("Phecode", "sex_at_birth_concept_id", "age_in_years <= MaximumAge", "age_in_years >= MinimumAge"), .(list(person_id)), by = .EACHI]
CTgov_to_AoU_Trial$NCTId <- trial_dat_expanded$NCTId
CTgov_to_AoU_Trial_ReturnOfValue <- CTgov_to_AoU_Trial
CTgov_to_AoU_Trial_ReturnOfValue <- CTgov_to_AoU_Trial_ReturnOfValue[, c("NCTId", "V1", "Phecode")]
CTgov_to_AoU_Trial <- CTgov_to_AoU_Trial[, .(nMatch = uniqueN(unlist(V1), na.rm = TRUE)), by = .(NCTId)]
write.csv(CTgov_to_AoU_Trial, file = "CTgov_to_AoU_Trial.csv")
CTgov_to_AoU_Trial <- CTgov_to_AoU_Trial[order(CTgov_to_AoU_Trial$nMatch, decreasing = TRUE), ]
# barplot(CTgov_to_AoU_Trial$nMatch, xlab = "Study", ylab = "Number of Eligible Participants", main = "Number of Eligible Participants by Trial", ylim = c(0, 200000))
CTgov_to_AoU_Trial$category <- ifelse(CTgov_to_AoU_Trial$nMatch == 0, 0, 
                                ifelse(CTgov_to_AoU_Trial$nMatch <= 500, 1, 
                                       ifelse(CTgov_to_AoU_Trial$nMatch <= 1000, 2, 3)))
# table(CTgov_to_AoU_Trial$category)
```

```{r}
################################################################################
#                                 2023/09/20 update                            #
################################################################################

####################################################################################################
#                                            Table 1                                               #
####################################################################################################
##############################################################################################
#                                 (Add Race/Ethnicity)                                       #
##############################################################################################
person_condition_df_phecode_phenotype <- as.data.table(fread("person_condition_df_phecode_phenotype.csv", header = TRUE))
person_condition_df_phecode_phenotype <- person_condition_df_phecode_phenotype[, c("person_id", "sex_at_birth_concept_id", "age_in_years", "PheCode", "value_as_string", "race_concept_id", "ethnicity_concept_id")]
names(person_condition_df_phecode_phenotype) <- c("person_id", "sex_at_birth_concept_id", "age_in_years", "Phecode", "value_as_string", "race", "ethnicity")

person_condition_df_phecode_phenotype$zip <- sub("^.*([0-9]{3}).*", "\\1", person_condition_df_phecode_phenotype$value_as_string)
# Remove rows with invalid zip (000)
person_condition_df_phecode_phenotype <- person_condition_df_phecode_phenotype[-which(person_condition_df_phecode_phenotype$zip %in% "000"), ]
person_condition_df_phecode_phenotype <- person_condition_df_phecode_phenotype[, c("person_id", "sex_at_birth_concept_id", "age_in_years", "Phecode", "zip", "race", "ethnicity")]
person_condition_df_phecode_phenotype$race_ethnicity <- ifelse(person_condition_df_phecode_phenotype$race == 8527 & person_condition_df_phecode_phenotype$ethnicity == 38003564, "White",
                                                              ifelse(person_condition_df_phecode_phenotype$race == 8516 & person_condition_df_phecode_phenotype$ethnicity == 38003564, "Black",
                                                                    ifelse(person_condition_df_phecode_phenotype$race == 8515 & person_condition_df_phecode_phenotype$ethnicity == 38003564, "Asian",
                                                                          ifelse(person_condition_df_phecode_phenotype$race == 8557 & person_condition_df_phecode_phenotype$ethnicity == 38003564, "NHOPI",
                                                                                ifelse(person_condition_df_phecode_phenotype$race == 38003615 & person_condition_df_phecode_phenotype$ethnicity == 38003564, "MENA",
                                                                                       ifelse(person_condition_df_phecode_phenotype$race == 2000000008 & person_condition_df_phecode_phenotype$ethnicity == 38003564, "Multiple",
                                                                                              ifelse(person_condition_df_phecode_phenotype$ethnicity == 38003563, "Hispanic", "Other")))))))
person_condition_df_phecode_phenotype$sex_at_birth <- ifelse(person_condition_df_phecode_phenotype$sex_at_birth_concept_id  == 45878463, "Female",
                                                            ifelse(person_condition_df_phecode_phenotype$sex_at_birth_concept_id == 45880669, "Male",
                                                                  ifelse(person_condition_df_phecode_phenotype$sex_at_birth_concept_id == 903096, "NoAnswer",
                                                                        ifelse(person_condition_df_phecode_phenotype$sex_at_birth_concept_id == 0, "NoAnswer",
                                                                              ifelse(person_condition_df_phecode_phenotype$sex_at_birth_concept_id == 46273637, "Intersex",
                                                                                    ifelse(person_condition_df_phecode_phenotype$sex_at_birth_concept_id == 4124462, "None", "NoAnswer"))))))


##############################################################################################
#                                    (Add # of Conditions)                                   #
##############################################################################################
person_Cond <- as.data.table(person_condition_df_phecode_phenotype[, c("person_id", "Phecode")]) %>% distinct()
person_nCond <- as.data.table(person_Cond %>% group_by(person_id) %>% summarise(n_condition = n_distinct(Phecode)))

##############################################################################################
#                                    (Add Age Category)                                      #
##############################################################################################
person_condition_df_phecode_phenotype$age_cat <- ifelse(person_condition_df_phecode_phenotype$age_in_years < 50, 1, 2)
person_condition_df_phecode_phenotype$age_cat <- as.factor(person_condition_df_phecode_phenotype$age_cat)

##############################################################################################
#                                    (Add Location)                                          #
##############################################################################################
zip3_wRUCC <-  as.data.table(fread("zip3_wRUCC.csv", header = TRUE))
zip3_wRUCC <- zip3_wRUCC[, -1]
zip3_wRUCC$ZIP3 <- str_pad(zip3_wRUCC$ZIP3, 3, pad = "0")
zip3_wRUCC <- zip3_wRUCC[, c("ZIP3", "wRUCC")]
names(zip3_wRUCC) <- c("zip", "wRUCC")
person_condition_df_phecode_phenotype$zip <- as.factor(person_condition_df_phecode_phenotype$zip)
person_condition_df_phecode_phenotype <- zip3_wRUCC[person_condition_df_phecode_phenotype, on = "zip"]
person_condition_df_phecode_phenotype$location <- ifelse(person_condition_df_phecode_phenotype$wRUCC < 3, "Metro", "NonMetro")

##############################################################################################
#                                     (Survey Data)                                          #
##############################################################################################
# question_id <- c(1585940, 1585375, 1585889)
question_id <- c(1585940, 903573, 903574, 903575, 903576, 903577, 903578, 1585375, 1585889)
question_id_collapse <- paste0(question_id, collapse = ",")
survey_query <- str_glue("SELECT 
                              answer,
                              question_concept_id,
                              person_id,
                              survey_datetime
                          FROM 
                              `{dataset}.ds_survey` ds_survey 
                          WHERE 
                              ds_survey.question_concept_id IN ({question_id_collapse})")
survey_data <- download_data(survey_query)
survey_data$year <- format(as.Date(survey_data$survey_datetime, format="%d/%m/%Y"),"%Y")



#############
# Education #
#############
# 1585940 What is the highest grade or year of school you completed?
survey_education <- survey_data[which(survey_data$question_concept_id == 1585940), ]
survey_education$education <- ifelse(survey_education$answer %in% c("Highest Grade: Never Attended", "Highest Grade: One Through Four", "Highest Grade: Five Through Eight", "Highest Grade: Nine Through Eleven"), "Eleven or below",
                                    ifelse(survey_education$answer %in% c("Highest Grade: Twelve Or GED", "Highest Grade: College One to Three"), "Twelve or GED", 
                                           ifelse(survey_education$answer %in% c("Highest Grade: College Graduate"), "College Graduate", 
                                                 ifelse(survey_education$answer %in% c("Highest Grade: Advanced Degree"), "Advanced Degree", "NoAnswer"))))
survey_education <- survey_education[, c("person_id", "education")]
survey_education <- as.data.table(survey_education)
survey_education <- survey_education[which(survey_education$education %in% c("Eleven or below", "Twelve or GED", "College Graduate", "Advanced Degree"))]
survey_education <- survey_education %>% distinct()

##############
#   Income   #
##############
# 1585375 What is your annual household income from all sources?
# 1585889 Not including yourself, how many other people live at home with you?
survey_income <- survey_data[which(survey_data$question_concept_id == 1585375), ]
survey_income <- survey_income[, c("person_id", "answer", "year")]
survey_income$max_income <- ifelse(survey_income$answer %in% c("Annual Income: 10k 25k"), 25000,
                                  ifelse(survey_income$answer %in% c("Annual Income: 25k 35k"), 35000,
                                        ifelse(survey_income$answer %in% c("Annual Income: 35k 50k"), 50000,
                                              ifelse(survey_income$answer %in% c("Annual Income: 50k 75k"), 75000,
                                                    ifelse(survey_income$answer %in% c("Annual Income: 75k 100k"), 100000,
                                                          ifelse(survey_income$answer %in% c("Annual Income: 100k 150k"), 150000,
                                                                ifelse(survey_income$answer %in% c("Annual Income: 150k 200k"), 200000,
                                                                      ifelse(survey_income$answer %in% c("Annual Income: more 200k"), 200001,
                                                                            ifelse(survey_income$answer %in% c("Annual Income: less 10k"), 9999, "NoAnswer")))))))))
survey_income <- survey_income[, c("person_id", "max_income", "year")]
survey_income <- as.data.table(survey_income)
survey_income_mostRecent <- survey_income %>%
  group_by(person_id) %>%
  filter(year == max(year))
survey_income_mostRecent <- as.data.table(survey_income_mostRecent)
survey_size <- survey_data[which(survey_data$question_concept_id == 1585889), ]
survey_size$family_size <- ifelse(survey_size$answer %in% "0", 1, 
                                  ifelse(survey_size$answer %in% "1", 2, 
                                        ifelse(survey_size$answer %in% "2", 3, 
                                              ifelse(survey_size$answer %in% "3", 4,
                                                    ifelse(survey_size$answer %in% "4", 5,
                                                          ifelse(survey_size$answer %in% "5", 6,
                                                                ifelse(survey_size$answer %in% "6", 7,
                                                                      ifelse(survey_size$answer %in% "7", 8,
                                                                            ifelse(survey_size$answer %in% "8", 9,
                                                                                  ifelse(survey_size$answer %in% "9", 10,
                                                                                        ifelse(survey_size$answer %in% "10", 11, "NoAnswer")))))))))))
survey_size <- survey_size[, c("person_id", "family_size")]
survey_size <- survey_size %>% distinct()
survey_size <- as.data.table(survey_size)
person_id_zip <- person_condition_df_phecode_phenotype[, c("person_id", "zip")]
person_id_zip <- person_id_zip %>% distinct()
survey_size_zip <- person_id_zip[survey_size, on = "person_id"]
survey_size_zip_income <- survey_income[survey_size_zip, on = "person_id"]

income_zip_family_size <- fread("income_zip_long_new.csv", header = TRUE)
income_zip_family_size <- income_zip_family_size[, -1]
income_zip_family_size$zip <- as.character(income_zip_family_size$zip)
income_zip_family_size$year <- as.character(income_zip_family_size$year)

survey_size_zip_income_limit <- income_zip_family_size[survey_size_zip_income, on = c("family_size", "zip", "year")]
survey_size_zip_income_limit <- survey_size_zip_income_limit[-which(survey_size_zip_income_limit$max_income %in% "NoAnswer"), ]
survey_size_zip_income_limit <- survey_size_zip_income_limit[-which(is.na(survey_size_zip_income_limit$zip)), ]
survey_size_zip_income_limit$max_income <- as.double(survey_size_zip_income_limit$max_income)
survey_size_zip_income_limit$low_income <- ifelse(survey_size_zip_income_limit$max_income < survey_size_zip_income_limit$income_limit, "Yes", "No")

survey_low_income <- survey_size_zip_income_limit[, c("person_id", "low_income")]
survey_low_income <- as.data.table(survey_low_income)
survey_low_income <- survey_low_income %>% distinct()

##############
# Disability #
##############
# 903573 Are you deaf or do you have serious difficulty hearing?
# 903574 Are you blind or do you have serious difficulty seeing, even when wearing glasses?
# 903575 Because of a physical, mental, or emotional condition, do you have serious difficulty concentrating, remembering or making decisions?
# 903576 Do you have serious difficulty walking or climbing stairs?
# 903577 Do you have difficulty dressing or bathing?
# 903578 Because of a physical, mental, or emotional condition, do you have difficulty doing errands alone such as visiting doctorвЂ™s office or shopping?
survey_disability <- survey_data[which(survey_data$question_concept_id %in% c(903573, 903574, 903575, 903576, 903577, 903578)), ]
survey_disability$disability <- ifelse(survey_disability$answer %in% c("Deaf: Yes", "Blind: Yes", "Errands Alone: Yes",
                                                                       "Dressing Bathing: Yes", "Walking Climbing: Yes", 
                                                                       "Difficulty Concentrating: Yes"), "Yes",
                                      ifelse(survey_disability$answer %in% c("Deaf: No", "Blind: No", "Errands Alone: No",
                                                                       "Dressing Bathing: No", "Walking Climbing: No", 
                                                                       "Difficulty Concentrating: No"), "No", "NoAnswer"))

survey_disability <- survey_disability[, c("person_id", "disability")]
survey_disability <- survey_disability %>% dplyr::group_by(person_id) %>% dplyr::mutate(any_disability = ifelse(any(disability %in% "Yes"), "Yes", disability))
survey_disability <- survey_disability[, c("person_id", "any_disability")]
survey_disability <- as.data.table(survey_disability)
survey_disability <- survey_disability %>% distinct()

# Merge all data together
person_table1 <- person_condition_df_phecode_phenotype[, c("person_id", "location", "age_cat", "race_ethnicity", "sex_at_birth")]
person_table1 <- survey_education[person_table1, on = "person_id"]
person_table1 <- survey_low_income[person_table1, on = "person_id"]
person_table1 <- survey_disability[person_table1, on = "person_id"]
person_table1 <- person_table1 %>% distinct()
person_table1 <- as.data.table(person_table1)

person_figure2 <- person_condition_df_phecode_phenotype[, c("person_id", "location", "age_in_years", "race_ethnicity", "sex_at_birth")]
person_figure2 <- person_figure2[which(person_figure2$sex_at_birth %in% c("Female", "Male", "Intersex")), ]
person_figure2 <- survey_education[person_figure2, on = "person_id"]
person_figure2 <- survey_low_income[person_figure2, on = "person_id"]
person_figure2 <- person_nCond[person_figure2, on = "person_id"]
person_figure2 <- person_figure2 %>% distinct()
person_figure2 <- as.data.table(person_figure2)

write.csv(person_table1, file = "person_table1.csv")
write.csv(person_figure2, file = "person_figure2.csv")
```

```{r}
################################################################################
#                                 2024/02/20 update                            #
#                           Add clinical profiles to Table 1                   #
################################################################################

# AoU data
person_condition_df_phecode_phenotype <- as.data.table(fread("person_condition_df_phecode_phenotype.csv", header = TRUE))
person_condition_df_phecode_phenotype <- person_condition_df_phecode_phenotype[, c("person_id", "sex_at_birth_concept_id", "age_in_years", "PheCode", "value_as_string", "race_concept_id", "ethnicity_concept_id")]
names(person_condition_df_phecode_phenotype) <- c("person_id", "sex_at_birth_concept_id", "age_in_years", "Phecode", "value_as_string", "race", "ethnicity")

person_condition_df_phecode_phenotype$zip <- sub("^.*([0-9]{3}).*", "\\1", person_condition_df_phecode_phenotype$value_as_string)
# Remove rows with invalid zip (000)
person_condition_df_phecode_phenotype <- person_condition_df_phecode_phenotype[-which(person_condition_df_phecode_phenotype$zip %in% "000"), ]
##############################################################################################
#                                             (Add R/E)                                      #
##############################################################################################
person_condition_df_phecode_phenotype$race_ethnicity <- ifelse(person_condition_df_phecode_phenotype$race == 8527 & person_condition_df_phecode_phenotype$ethnicity == 38003564, "White",
                                                              ifelse(person_condition_df_phecode_phenotype$race == 8516 & person_condition_df_phecode_phenotype$ethnicity == 38003564, "Black",
                                                                    ifelse(person_condition_df_phecode_phenotype$race == 8515 & person_condition_df_phecode_phenotype$ethnicity == 38003564, "Asian",
                                                                          ifelse(person_condition_df_phecode_phenotype$race == 8557 & person_condition_df_phecode_phenotype$ethnicity == 38003564, "NHOPI",
                                                                                ifelse(person_condition_df_phecode_phenotype$race == 38003615 & person_condition_df_phecode_phenotype$ethnicity == 38003564, "MENA",
                                                                                       ifelse(person_condition_df_phecode_phenotype$race == 2000000008 & person_condition_df_phecode_phenotype$ethnicity == 38003564, "Multiple",
                                                                                              ifelse(person_condition_df_phecode_phenotype$ethnicity == 38003563, "Hispanic", "Other")))))))
##############################################################################################
#                                    (Add Sex Category)                                      #
##############################################################################################
person_condition_df_phecode_phenotype$sex_at_birth <- ifelse(person_condition_df_phecode_phenotype$sex_at_birth_concept_id  == 45878463, "Female",
                                                            ifelse(person_condition_df_phecode_phenotype$sex_at_birth_concept_id == 45880669, "Male",
                                                                  ifelse(person_condition_df_phecode_phenotype$sex_at_birth_concept_id == 903096, "NoAnswer",
                                                                        ifelse(person_condition_df_phecode_phenotype$sex_at_birth_concept_id == 0, "NoAnswer",
                                                                              ifelse(person_condition_df_phecode_phenotype$sex_at_birth_concept_id == 46273637, "Intersex",
                                                                                    ifelse(person_condition_df_phecode_phenotype$sex_at_birth_concept_id == 4124462, "None", "NoAnswer"))))))


##############################################################################################
#                                    (Add Age Category)                                      #
##############################################################################################
person_condition_df_phecode_phenotype$age_cat <- ifelse(person_condition_df_phecode_phenotype$age_in_years < 40, 1,
                                                        ifelse(person_condition_df_phecode_phenotype$age_in_years < 70, 2, 3))
person_condition_df_phecode_phenotype$age_cat <- as.factor(person_condition_df_phecode_phenotype$age_cat)

##############################################################################################
#                                    (Add Location)                                          #
##############################################################################################
zip3_wRUCC <-  as.data.table(fread("zip3_wRUCC.csv", header = TRUE))
zip3_wRUCC <- zip3_wRUCC[, -1]
zip3_wRUCC$ZIP3 <- str_pad(zip3_wRUCC$ZIP3, 3, pad = "0")
zip3_wRUCC <- zip3_wRUCC[, c("ZIP3", "wRUCC")]
names(zip3_wRUCC) <- c("zip", "wRUCC")

# Merge AoU data with zip3-to-RUCC key
person_condition_df_phecode_phenotype$zip <- as.factor(person_condition_df_phecode_phenotype$zip)
person_condition_df_phecode_phenotype <- zip3_wRUCC[person_condition_df_phecode_phenotype, on = "zip"]
person_condition_df_phecode_phenotype$location <- ifelse(person_condition_df_phecode_phenotype$wRUCC < 3, "Metro", "NonMetro")

person_condition_df_phecode_phenotype$Phecode <- as.character(person_condition_df_phecode_phenotype$Phecode)
person_condition_df_phecode_phenotype_category <- addPhecodeInfo(person_condition_df_phecode_phenotype)
table1_cond <- person_condition_df_phecode_phenotype_category %>%
                    group_by(group) %>%
                    summarise(unique_persons = n_distinct(person_id))
table1_cond$prop <- table1_cond$unique_persons/length(unique(person_condition_df_phecode_phenotype_category$person_id))
table1_cond

# person_condition_df_phecode_phenotype_category$group[which(person_condition_df_phecode_phenotype_category$group %in% c("digestive", "hematopoietic", "sense organs", "symptoms", "musculoskeletal", "genitourinary", "injuries & poisonings", "pregnancy complications", "dermatologic", "congenital anomalies", "infectious diseases"))] <- "other"
person_condition_df_phecode_phenotype_category$group[which(!(person_condition_df_phecode_phenotype_category$group %in% c("endocrine/metabolic", "neoplasms", "mental disorders", "respiratory", "circulatory system", "neurological")))] <- "other"
table1_cond <- person_condition_df_phecode_phenotype_category %>%
                    group_by(group) %>%
                    summarise(unique_persons = n_distinct(person_id))
table1_cond$prop <- table1_cond$unique_persons/length(unique(person_condition_df_phecode_phenotype_category$person_id))
table1_cond
```

```{r}
################################################################################
#                                 2023/09/20 update                            #
################################################################################


#########################################
#                Overall                #
#########################################
AoU_to_CTgov_wZip_Trial_overall <- trial_dat_expanded_zip[person_condition_df_phecode_phenotype_category, on = c("Phecode", "sex_at_birth_concept_id", "zip", "MaximumAge >= age_in_years", "MinimumAge <= age_in_years"), .(list(NCTId)), by = .EACHI]
AoU_to_CTgov_wZip_Trial_overall$person_id <- person_condition_df_phecode_phenotype_category$person_id
AoU_to_CTgov_wZip_Trial_ReturnOfValue_overall <- AoU_to_CTgov_wZip_Trial_overall
AoU_to_CTgov_wZip_Trial_ReturnOfValue_overall <- AoU_to_CTgov_wZip_Trial_ReturnOfValue_overall[, c("person_id", "V1", "Phecode")]
AoU_to_CTgov_wZip_Trial_overall <- AoU_to_CTgov_wZip_Trial_overall[, .(nMatch = uniqueN(unlist(V1), na.rm = TRUE)), by = .(person_id)]
write.csv(AoU_to_CTgov_wZip_Trial_overall, file = "AoU_to_CTgov_wZip_Trial_overall.csv")
AoU_to_CTgov_wZip_Trial_overall <- AoU_to_CTgov_wZip_Trial_overall[order(AoU_to_CTgov_wZip_Trial_overall$nMatch, decreasing = TRUE), ]


#########################################
#                Other                  #
#########################################
# For each participant, count the number of studies s/he matches with
AoU_to_CTgov_wZip_Trial_other <- trial_dat_expanded_zip[person_condition_df_phecode_phenotype_other, on = c("Phecode", "sex_at_birth_concept_id", "zip", "MaximumAge >= age_in_years", "MinimumAge <= age_in_years"), .(list(NCTId)), by = .EACHI]
AoU_to_CTgov_wZip_Trial_other$person_id <- person_condition_df_phecode_phenotype_other$person_id
AoU_to_CTgov_wZip_Trial_ReturnOfValue_other <- AoU_to_CTgov_wZip_Trial_other
AoU_to_CTgov_wZip_Trial_ReturnOfValue_other <- AoU_to_CTgov_wZip_Trial_ReturnOfValue_other[, c("person_id", "V1", "Phecode")]
AoU_to_CTgov_wZip_Trial_other <- AoU_to_CTgov_wZip_Trial_other[, .(nMatch = uniqueN(unlist(V1), na.rm = TRUE)), by = .(person_id)]
write.csv(AoU_to_CTgov_wZip_Trial_other, file = "AoU_to_CTgov_wZip_Trial_other.csv")
AoU_to_CTgov_wZip_Trial_other <- AoU_to_CTgov_wZip_Trial_other[order(AoU_to_CTgov_wZip_Trial_other$nMatch, decreasing = TRUE), ]

#########################################
#                neurological           #
#########################################
# For each participant, count the number of studies s/he matches with
AoU_to_CTgov_wZip_Trial_neurological <- trial_dat_expanded_zip[person_condition_df_phecode_phenotype_neurological, on = c("Phecode", "sex_at_birth_concept_id", "zip", "MaximumAge >= age_in_years", "MinimumAge <= age_in_years"), .(list(NCTId)), by = .EACHI]
AoU_to_CTgov_wZip_Trial_neurological$person_id <- person_condition_df_phecode_phenotype_neurological$person_id
AoU_to_CTgov_wZip_Trial_ReturnOfValue_neurological <- AoU_to_CTgov_wZip_Trial_neurological
AoU_to_CTgov_wZip_Trial_ReturnOfValue_neurological <- AoU_to_CTgov_wZip_Trial_ReturnOfValue_neurological[, c("person_id", "V1", "Phecode")]
AoU_to_CTgov_wZip_Trial_neurological <- AoU_to_CTgov_wZip_Trial_neurological[, .(nMatch = uniqueN(unlist(V1), na.rm = TRUE)), by = .(person_id)]
write.csv(AoU_to_CTgov_wZip_Trial_neurological, file = "AoU_to_CTgov_wZip_Trial_neurological.csv")
AoU_to_CTgov_wZip_Trial_neurological <- AoU_to_CTgov_wZip_Trial_neurological[order(AoU_to_CTgov_wZip_Trial_neurological$nMatch, decreasing = TRUE), ]

#########################################
#                circulatory            #
#########################################
# For each participant, count the number of studies s/he matches with
AoU_to_CTgov_wZip_Trial_circulatory <- trial_dat_expanded_zip[person_condition_df_phecode_phenotype_circulatory, on = c("Phecode", "sex_at_birth_concept_id", "zip", "MaximumAge >= age_in_years", "MinimumAge <= age_in_years"), .(list(NCTId)), by = .EACHI]
AoU_to_CTgov_wZip_Trial_circulatory$person_id <- person_condition_df_phecode_phenotype_circulatory$person_id
AoU_to_CTgov_wZip_Trial_ReturnOfValue_circulatory <- AoU_to_CTgov_wZip_Trial_circulatory
AoU_to_CTgov_wZip_Trial_ReturnOfValue_circulatory <- AoU_to_CTgov_wZip_Trial_ReturnOfValue_circulatory[, c("person_id", "V1", "Phecode")]
AoU_to_CTgov_wZip_Trial_circulatory <- AoU_to_CTgov_wZip_Trial_circulatory[, .(nMatch = uniqueN(unlist(V1), na.rm = TRUE)), by = .(person_id)]
write.csv(AoU_to_CTgov_wZip_Trial_circulatory, file = "AoU_to_CTgov_wZip_Trial_circulatory.csv")
AoU_to_CTgov_wZip_Trial_circulatory <- AoU_to_CTgov_wZip_Trial_circulatory[order(AoU_to_CTgov_wZip_Trial_circulatory$nMatch, decreasing = TRUE), ]

#########################################
#                respiratory            #
#########################################
# For each participant, count the number of studies s/he matches with
AoU_to_CTgov_wZip_Trial_respiratory <- trial_dat_expanded_zip[person_condition_df_phecode_phenotype_respiratory, on = c("Phecode", "sex_at_birth_concept_id", "zip", "MaximumAge >= age_in_years", "MinimumAge <= age_in_years"), .(list(NCTId)), by = .EACHI]
AoU_to_CTgov_wZip_Trial_respiratory$person_id <- person_condition_df_phecode_phenotype_respiratory$person_id
AoU_to_CTgov_wZip_Trial_ReturnOfValue_respiratory <- AoU_to_CTgov_wZip_Trial_respiratory
AoU_to_CTgov_wZip_Trial_ReturnOfValue_respiratory <- AoU_to_CTgov_wZip_Trial_ReturnOfValue_respiratory[, c("person_id", "V1", "Phecode")]
AoU_to_CTgov_wZip_Trial_respiratory <- AoU_to_CTgov_wZip_Trial_respiratory[, .(nMatch = uniqueN(unlist(V1), na.rm = TRUE)), by = .(person_id)]
write.csv(AoU_to_CTgov_wZip_Trial_respiratory, file = "AoU_to_CTgov_wZip_Trial_respiratory.csv")
AoU_to_CTgov_wZip_Trial_respiratory <- AoU_to_CTgov_wZip_Trial_respiratory[order(AoU_to_CTgov_wZip_Trial_respiratory$nMatch, decreasing = TRUE), ]

#########################################
#                mental                 #
#########################################
# For each participant, count the number of studies s/he matches with
AoU_to_CTgov_wZip_Trial_mental <- trial_dat_expanded_zip[person_condition_df_phecode_phenotype_mental, on = c("Phecode", "sex_at_birth_concept_id", "zip", "MaximumAge >= age_in_years", "MinimumAge <= age_in_years"), .(list(NCTId)), by = .EACHI]
AoU_to_CTgov_wZip_Trial_mental$person_id <- person_condition_df_phecode_phenotype_mental$person_id
AoU_to_CTgov_wZip_Trial_ReturnOfValue_mental <- AoU_to_CTgov_wZip_Trial_mental
AoU_to_CTgov_wZip_Trial_ReturnOfValue_mental <- AoU_to_CTgov_wZip_Trial_ReturnOfValue_mental[, c("person_id", "V1", "Phecode")]
AoU_to_CTgov_wZip_Trial_mental <- AoU_to_CTgov_wZip_Trial_mental[, .(nMatch = uniqueN(unlist(V1), na.rm = TRUE)), by = .(person_id)]
write.csv(AoU_to_CTgov_wZip_Trial_mental, file = "AoU_to_CTgov_wZip_Trial_mental.csv")
AoU_to_CTgov_wZip_Trial_mental <- AoU_to_CTgov_wZip_Trial_mental[order(AoU_to_CTgov_wZip_Trial_mental$nMatch, decreasing = TRUE), ]

#########################################
#                neoplasms              #
#########################################
# For each participant, count the number of studies s/he matches with
AoU_to_CTgov_wZip_Trial_neoplasms <- trial_dat_expanded_zip[person_condition_df_phecode_phenotype_neoplasms, on = c("Phecode", "sex_at_birth_concept_id", "zip", "MaximumAge >= age_in_years", "MinimumAge <= age_in_years"), .(list(NCTId)), by = .EACHI]
AoU_to_CTgov_wZip_Trial_neoplasms$person_id <- person_condition_df_phecode_phenotype_neoplasms$person_id
AoU_to_CTgov_wZip_Trial_ReturnOfValue_neoplasms <- AoU_to_CTgov_wZip_Trial_neoplasms
AoU_to_CTgov_wZip_Trial_ReturnOfValue_neoplasms <- AoU_to_CTgov_wZip_Trial_ReturnOfValue_neoplasms[, c("person_id", "V1", "Phecode")]
AoU_to_CTgov_wZip_Trial_neoplasms <- AoU_to_CTgov_wZip_Trial_neoplasms[, .(nMatch = uniqueN(unlist(V1), na.rm = TRUE)), by = .(person_id)]
write.csv(AoU_to_CTgov_wZip_Trial_neoplasms, file = "AoU_to_CTgov_wZip_Trial_neoplasms.csv")
AoU_to_CTgov_wZip_Trial_neoplasms <- AoU_to_CTgov_wZip_Trial_neoplasms[order(AoU_to_CTgov_wZip_Trial_neoplasms$nMatch, decreasing = TRUE), ]

############################################
#              endocrine/metabolic         #
############################################
# For each participant, count the number of studies s/he matches with
AoU_to_CTgov_wZip_Trial_em <- trial_dat_expanded_zip[person_condition_df_phecode_phenotype_em, on = c("Phecode", "sex_at_birth_concept_id", "zip", "MaximumAge >= age_in_years", "MinimumAge <= age_in_years"), .(list(NCTId)), by = .EACHI]
AoU_to_CTgov_wZip_Trial_em$person_id <- person_condition_df_phecode_phenotype_em$person_id
AoU_to_CTgov_wZip_Trial_ReturnOfValue_em <- AoU_to_CTgov_wZip_Trial_em
AoU_to_CTgov_wZip_Trial_ReturnOfValue_em <- AoU_to_CTgov_wZip_Trial_ReturnOfValue_em[, c("person_id", "V1", "Phecode")]
AoU_to_CTgov_wZip_Trial_em <- AoU_to_CTgov_wZip_Trial_em[, .(nMatch = uniqueN(unlist(V1), na.rm = TRUE)), by = .(person_id)]
write.csv(AoU_to_CTgov_wZip_Trial_em, file = "AoU_to_CTgov_wZip_Trial_em.csv")
AoU_to_CTgov_wZip_Trial_em <- AoU_to_CTgov_wZip_Trial_em[order(AoU_to_CTgov_wZip_Trial_em$nMatch, decreasing = TRUE), ]
```

```{r}
################################################################################
#                                 2023/12/02 update                            #
################################################################################
################################################################################
#                                   Add SDOH                                   #
################################################################################
SDOH_survey <- read.csv("SDOH_survey.csv", header = TRUE)
person_table1 <- read.csv("person_table1.csv", header = TRUE)
person_table1 <- as.data.table(person_table1)
person_figure2 <- read.csv("person_figure2.csv", header = TRUE)
person_figure2 <- as.data.table(person_figure2)

# 40192526 English proficiency - 1 item (Yes/No)
# Do you speak a language other than English at home?
# --- Branching: 40192529 Since you speak a language other than English at home, we are interested in your own thoughts about how well you think you speak English. Would you say you speak English...
# Not at all, Not well, Well, Very Well
SDOH_EngProf1 <- SDOH_survey[which(SDOH_survey$question_concept_id == 40192526), c("person_id", "answer")]
SDOH_EngProf1 <- SDOH_EngProf1[-which(SDOH_EngProf1$answer %in% c("PMI: Skip", "PMI: Prefer Not To Answer")), ]
names(SDOH_EngProf1) <- c("person_id", "EngProf")
SDOH_EngProf1$EngProf <- ifelse(SDOH_EngProf1$EngProf %in% c("No"), "Yes", "No")
SDOH_EngProf1 <- SDOH_EngProf1[which(SDOH_EngProf1$EngProf %in% "Yes"), ]
SDOH_EngProf1$EngProf <- as.factor(SDOH_EngProf1$EngProf)
SDOH_EngProf1 <- as.data.table(SDOH_EngProf1)

SDOH_EngProf2 <- SDOH_survey[which(SDOH_survey$question_concept_id == 40192529), c("person_id", "answer")]
SDOH_EngProf2 <- SDOH_EngProf2[-which(SDOH_EngProf2$answer %in% c("PMI: Dont Know", "PMI: Skip", "PMI: Prefer Not To Answer")), ]
names(SDOH_EngProf2) <- c("person_id", "EngProf")
SDOH_EngProf2$EngProf <- ifelse(SDOH_EngProf2$EngProf %in% c("Well", "Very well"), "Yes", "No")
SDOH_EngProf <- rbind(SDOH_EngProf1, SDOH_EngProf2)
SDOH_EngProf$EngProf <- as.factor(SDOH_EngProf$EngProf)
SDOH_EngProf <- as.data.table(SDOH_EngProf)
person_table1 <- SDOH_EngProf[person_table1, on = "person_id"]
person_figure2 <- SDOH_EngProf[person_figure2, on = "person_id"]

# 40192441 Housing instability - 1 item (Number of times moved)
# In the last 12 months, how many times have you or your family moved from one home to another? Number of moves in past 12 months:'
SDOH_housing_instability <- SDOH_survey[which(SDOH_survey$question_concept_id == 40192441), c("person_id", "answer")]
SDOH_housing_instability <- SDOH_housing_instability[-which(SDOH_housing_instability$answer %in% c("PMI: Skip")), ]
SDOH_housing_instability$answer <- as.numeric(SDOH_housing_instability$answer)
SDOH_housing_instability$answer <- ifelse(SDOH_housing_instability$answer >= 2, "Yes", "No")
names(SDOH_housing_instability) <- c("person_id", "HousingInstability")
SDOH_housing_instability$HousingInstability <- as.factor(SDOH_housing_instability$HousingInstability)
SDOH_housing_instability <- as.data.table(SDOH_housing_instability)
person_table1 <- SDOH_housing_instability[person_table1, on = "person_id"]
# (numerical # of moves)
SDOH_housing_instability <- SDOH_survey[which(SDOH_survey$question_concept_id == 40192441), c("person_id", "answer")]
SDOH_housing_instability <- SDOH_housing_instability[-which(SDOH_housing_instability$answer %in% c("PMI: Skip")), ]
SDOH_housing_instability$answer <- as.numeric(SDOH_housing_instability$answer)
names(SDOH_housing_instability) <- c("person_id", "HousingInstability")
SDOH_housing_instability <- as.data.table(SDOH_housing_instability)
person_figure2 <- SDOH_housing_instability[person_figure2, on = "person_id"]

# Food insecurity - 2 items (Never True, Sometimes True, Often True)
# 40192517 Within the past 12 months, we worried whether our food would run out before we got money to buy more.
# 40192426 Within the past 12 months, the food we bought just didn't last and we didn't have money to get more.
# FI defined as answering Sometimes True/Often True to either of the 2 questions
# Recoded so that 0 = no FI, 1 = FI (answering Sometimes True or Often True to either of the 2 questions)
SDOH_food_insecurity1 <- SDOH_survey[which(SDOH_survey$question_concept_id == 40192517), c("person_id", "answer")]
SDOH_food_insecurity1 <- SDOH_food_insecurity1[-which(SDOH_food_insecurity1$answer %in% c("PMI: Skip")), ]
SDOH_food_insecurity2 <- SDOH_survey[which(SDOH_survey$question_concept_id == 40192426), c("person_id", "answer")]
SDOH_food_insecurity2 <- SDOH_food_insecurity2[-which(SDOH_food_insecurity2$answer %in% c("PMI: Skip")), ]
SDOH_food_insecurity1 <- as.data.table(SDOH_food_insecurity1)
SDOH_food_insecurity2 <- as.data.table(SDOH_food_insecurity2)
SDOH_food_insecurity <- SDOH_food_insecurity2[SDOH_food_insecurity1, on = "person_id"]
names(SDOH_food_insecurity) <- c("person_id", "answer1", "answer2")
SDOH_food_insecurity$FI <- ifelse((SDOH_food_insecurity$answer1 %in% c("Never true")) & (SDOH_food_insecurity$answer2 %in% c("Never true")), "No", "Yes")
SDOH_food_insecurity <- SDOH_food_insecurity[, c("person_id", "FI")]
SDOH_food_insecurity$FI <- as.factor(SDOH_food_insecurity$FI)
SDOH_food_insecurity <- as.data.table(SDOH_food_insecurity)
person_table1 <- SDOH_food_insecurity[person_table1, on = "person_id"]
person_figure2 <- SDOH_food_insecurity[person_figure2, on = "person_id"]

# Everyday discrimination - 9 items (Almost everyday 5 , At least once a week 4, A few times a month 3, A few times a year 2, Less than once a year 1, Never 0)
# 40192466 In your day-to-day life, how often are you treated with less courtesy than other people?
# 40192489 In your day-to-day life, how often are you treated with less respect than other people?
# 40192416 In your day-to-day life, how often do you receive poorer service than other people at restaurants or stores?
# 40192490 In your day-to-day life, how often do people act as if they think you are not smart?
# 40192380 In your day-to-day life, how often do people act as if they are afraid of you?
# 40192395 In your day-to-day life, how often do people act as if they think you are dishonest?
# 40192496 In your day-to-day life, how often do people act as if they're better than you are?
# 40192519 In your day-to-day life, how often are you called names or insulted?
# 40192451 In your day-to-day life, how often are you threatened or harassed?
# The scale is flagged as missing if more than two items do not have a valid score
SDOH_eds1 <- SDOH_survey[which(SDOH_survey$question_concept_id == 40192466), c("person_id", "answer")]
SDOH_eds1 <- SDOH_eds1[-which(SDOH_eds1$answer %in% "PMI: Skip"), ]
SDOH_eds1$answer <- ifelse(SDOH_eds1$answer %in% "Almost everyday", 5,
                           ifelse(SDOH_eds1$answer %in% "At least once a week", 4, 
                                  ifelse(SDOH_eds1$answer %in% "A few times a month", 3,
                                         ifelse(SDOH_eds1$answer %in% "A few times a year", 2, 
                                                ifelse(SDOH_eds1$answer %in% "Less than once a year", 1, 0)))))
SDOH_eds1 <- as.data.table(SDOH_eds1)

SDOH_eds2 <- SDOH_survey[which(SDOH_survey$question_concept_id == 40192489), c("person_id", "answer")]
SDOH_eds2 <- SDOH_eds2[-which(SDOH_eds2$answer %in% "PMI: Skip"), ]
SDOH_eds2$answer <- ifelse(SDOH_eds2$answer %in% "Almost everyday", 5,
                           ifelse(SDOH_eds2$answer %in% "At least once a week", 4, 
                                  ifelse(SDOH_eds2$answer %in% "A few times a month", 3,
                                         ifelse(SDOH_eds2$answer %in% "A few times a year", 2, 
                                                ifelse(SDOH_eds2$answer %in% "Less than once a year", 1, 0)))))
SDOH_eds2 <- as.data.table(SDOH_eds2)

SDOH_eds3 <- SDOH_survey[which(SDOH_survey$question_concept_id == 40192416), c("person_id", "answer")]
SDOH_eds3 <- SDOH_eds3[-which(SDOH_eds3$answer %in% "PMI: Skip"), ]
SDOH_eds3$answer <- ifelse(SDOH_eds3$answer %in% "Almost everyday", 5,
                           ifelse(SDOH_eds3$answer %in% "At least once a week", 4, 
                                  ifelse(SDOH_eds3$answer %in% "A few times a month", 3,
                                         ifelse(SDOH_eds3$answer %in% "A few times a year", 2, 
                                                ifelse(SDOH_eds3$answer %in% "Less than once a year", 1, 0)))))
SDOH_eds3 <- as.data.table(SDOH_eds3)

SDOH_eds4 <- SDOH_survey[which(SDOH_survey$question_concept_id == 40192490), c("person_id", "answer")]
SDOH_eds4 <- SDOH_eds4[-which(SDOH_eds4$answer %in% "PMI: Skip"), ]
SDOH_eds4$answer <- ifelse(SDOH_eds4$answer %in% "Almost everyday", 5,
                           ifelse(SDOH_eds4$answer %in% "At least once a week", 4, 
                                  ifelse(SDOH_eds4$answer %in% "A few times a month", 3,
                                         ifelse(SDOH_eds4$answer %in% "A few times a year", 2, 
                                                ifelse(SDOH_eds4$answer %in% "Less than once a year", 1, 0)))))
SDOH_eds4 <- as.data.table(SDOH_eds4)

SDOH_eds5 <- SDOH_survey[which(SDOH_survey$question_concept_id == 40192380), c("person_id", "answer")]
SDOH_eds5 <- SDOH_eds5[-which(SDOH_eds5$answer %in% "PMI: Skip"), ]
SDOH_eds5$answer <- ifelse(SDOH_eds5$answer %in% "Almost everyday", 5,
                           ifelse(SDOH_eds5$answer %in% "At least once a week", 4, 
                                  ifelse(SDOH_eds5$answer %in% "A few times a month", 3,
                                         ifelse(SDOH_eds5$answer %in% "A few times a year", 2, 
                                                ifelse(SDOH_eds5$answer %in% "Less than once a year", 1, 0)))))
SDOH_eds5 <- as.data.table(SDOH_eds5)

SDOH_eds6 <- SDOH_survey[which(SDOH_survey$question_concept_id == 40192395), c("person_id", "answer")]
SDOH_eds6 <- SDOH_eds6[-which(SDOH_eds6$answer %in% "PMI: Skip"), ]
SDOH_eds6$answer <- ifelse(SDOH_eds6$answer %in% "Almost everyday", 5,
                           ifelse(SDOH_eds6$answer %in% "At least once a week", 4, 
                                  ifelse(SDOH_eds6$answer %in% "A few times a month", 3,
                                         ifelse(SDOH_eds6$answer %in% "A few times a year", 2, 
                                                ifelse(SDOH_eds6$answer %in% "Less than once a year", 1, 0)))))
SDOH_eds6 <- as.data.table(SDOH_eds6)

SDOH_eds7 <- SDOH_survey[which(SDOH_survey$question_concept_id == 40192496), c("person_id", "answer")]
SDOH_eds7 <- SDOH_eds7[-which(SDOH_eds7$answer %in% "PMI: Skip"), ]
SDOH_eds7$answer <- ifelse(SDOH_eds7$answer %in% "Almost everyday", 5,
                           ifelse(SDOH_eds7$answer %in% "At least once a week", 4, 
                                  ifelse(SDOH_eds7$answer %in% "A few times a month", 3,
                                         ifelse(SDOH_eds7$answer %in% "A few times a year", 2, 
                                                ifelse(SDOH_eds7$answer %in% "Less than once a year", 1, 0)))))
SDOH_eds7 <- as.data.table(SDOH_eds7)

SDOH_eds8 <- SDOH_survey[which(SDOH_survey$question_concept_id == 40192519), c("person_id", "answer")]
SDOH_eds8 <- SDOH_eds8[-which(SDOH_eds8$answer %in% "PMI: Skip"), ]
SDOH_eds8$answer <- ifelse(SDOH_eds8$answer %in% "Almost everyday", 5,
                           ifelse(SDOH_eds8$answer %in% "At least once a week", 4, 
                                  ifelse(SDOH_eds8$answer %in% "A few times a month", 3,
                                         ifelse(SDOH_eds8$answer %in% "A few times a year", 2, 
                                                ifelse(SDOH_eds8$answer %in% "Less than once a year", 1, 0)))))
SDOH_eds8 <- as.data.table(SDOH_eds8)

SDOH_eds9 <- SDOH_survey[which(SDOH_survey$question_concept_id == 40192451), c("person_id", "answer")]
SDOH_eds9 <- SDOH_eds9[-which(SDOH_eds9$answer %in% "PMI: Skip"), ]
SDOH_eds9$answer <- ifelse(SDOH_eds9$answer %in% "Almost everyday", 5,
                           ifelse(SDOH_eds9$answer %in% "At least once a week", 4, 
                                  ifelse(SDOH_eds9$answer %in% "A few times a month", 3,
                                         ifelse(SDOH_eds9$answer %in% "A few times a year", 2, 
                                                ifelse(SDOH_eds9$answer %in% "Less than once a year", 1, 0)))))
SDOH_eds9 <- as.data.table(SDOH_eds9)


SDOH_eds12 <- SDOH_eds2[SDOH_eds1, on = "person_id"]
SDOH_eds123 <- SDOH_eds3[SDOH_eds12, on = "person_id"]
SDOH_eds1234 <- SDOH_eds4[SDOH_eds123, on = "person_id"]
SDOH_eds12345 <- SDOH_eds5[SDOH_eds1234, on = "person_id"]
SDOH_eds123456 <- SDOH_eds6[SDOH_eds12345, on = "person_id"]
SDOH_eds1234567 <- SDOH_eds7[SDOH_eds123456, on = "person_id"]
SDOH_eds12345678 <- SDOH_eds8[SDOH_eds1234567, on = "person_id"]
SDOH_eds123456789 <- SDOH_eds9[SDOH_eds12345678, on = "person_id"]
names(SDOH_eds123456789) <- c("person_id", "answer1", "answer2", "answer3", "answer4", "answer5", "answer6", "answer7", "answer8", "answer9")
# Define the custom function
mean_if_at_least_7 <- function(x) {
  if (sum(!is.na(x)) >= 7) {
    return(mean(x, na.rm = TRUE))
  } else {
    return(NA)
  }
}

# Apply the function to each row
SDOH_eds123456789$answer <- apply(SDOH_eds123456789[, -1], 1, mean_if_at_least_7)
SDOH_eds <- SDOH_eds123456789[-which(is.na(SDOH_eds123456789$answer)), c("person_id", "answer")]
names(SDOH_eds) <- c("person_id", "eds")
SDOH_eds$eds <- ifelse(SDOH_eds$eds > 1, "Yes", "No")
SDOH_eds$eds <- as.factor(SDOH_eds$eds)
SDOH_eds <- as.data.table(SDOH_eds)
person_table1 <- SDOH_eds[person_table1, on = "person_id"]
# (numerical EDS)
SDOH_eds12 <- SDOH_eds2[SDOH_eds1, on = "person_id"]
SDOH_eds123 <- SDOH_eds3[SDOH_eds12, on = "person_id"]
SDOH_eds1234 <- SDOH_eds4[SDOH_eds123, on = "person_id"]
SDOH_eds12345 <- SDOH_eds5[SDOH_eds1234, on = "person_id"]
SDOH_eds123456 <- SDOH_eds6[SDOH_eds12345, on = "person_id"]
SDOH_eds1234567 <- SDOH_eds7[SDOH_eds123456, on = "person_id"]
SDOH_eds12345678 <- SDOH_eds8[SDOH_eds1234567, on = "person_id"]
SDOH_eds123456789 <- SDOH_eds9[SDOH_eds12345678, on = "person_id"]
names(SDOH_eds123456789) <- c("person_id", "answer1", "answer2", "answer3", "answer4", "answer5", "answer6", "answer7", "answer8", "answer9")
SDOH_eds123456789$answer <- apply(SDOH_eds123456789[, -1], 1, mean_if_at_least_7)
SDOH_eds <- SDOH_eds123456789[-which(is.na(SDOH_eds123456789$answer)), c("person_id", "answer")]
names(SDOH_eds) <- c("person_id", "eds")
SDOH_eds <- as.data.table(SDOH_eds)
person_figure2 <- SDOH_eds[person_figure2, on = "person_id"]

# Social support - 8 items (None of the time 1, A little of the time 2, Some of the time 3, Most of the time 4, All of the time 5)
# 40192442 How often do you have someone to help you if you were confined to bed?
# 40192480 How often do you have someone to take you to the doctor if you need it?
# 40192388 How often do you have someone to prepare your meals if you were unable to do it yourself?
# 40192511 How often do you have someone to help you with daily chores if you were sick?
# 40192439 How often do you have someone to have a good time with?
# 40192528 How often do you have someone to turn to for suggestions about how to deal with a personal problem?
# 40192399 How often do you have someone who understands your problems?
# 40192446 How often do you have someone to love and make you feel wanted?
# Compute if 6 or more items have valid responses
SDOH_ss1 <- SDOH_survey[which(SDOH_survey$question_concept_id == 40192442), c("person_id", "answer")]
SDOH_ss1 <- SDOH_ss1[-which(SDOH_ss1$answer %in% "PMI: Skip"), ]
SDOH_ss1$answer <- ifelse(SDOH_ss1$answer %in% "None of the time", 1,
                           ifelse(SDOH_ss1$answer %in% "A little of the time", 2, 
                                  ifelse(SDOH_ss1$answer %in% "Some of the time", 3,
                                         ifelse(SDOH_ss1$answer %in% "Most of the time", 4, 5))))
SDOH_ss1 <- as.data.table(SDOH_ss1)

SDOH_ss2 <- SDOH_survey[which(SDOH_survey$question_concept_id == 40192480), c("person_id", "answer")]
SDOH_ss2 <- SDOH_ss2[-which(SDOH_ss2$answer %in% "PMI: Skip"), ]
SDOH_ss2$answer <- ifelse(SDOH_ss2$answer %in% "None of the time", 1,
                           ifelse(SDOH_ss2$answer %in% "A little of the time", 2, 
                                  ifelse(SDOH_ss2$answer %in% "Some of the time", 3,
                                         ifelse(SDOH_ss2$answer %in% "Most of the time", 4, 5))))
SDOH_ss2 <- as.data.table(SDOH_ss2)

SDOH_ss3 <- SDOH_survey[which(SDOH_survey$question_concept_id == 40192388), c("person_id", "answer")]
SDOH_ss3 <- SDOH_ss3[-which(SDOH_ss3$answer %in% "PMI: Skip"), ]
SDOH_ss3$answer <- ifelse(SDOH_ss3$answer %in% "None of the time", 1,
                          ifelse(SDOH_ss3$answer %in% "A little of the time", 2, 
                                 ifelse(SDOH_ss3$answer %in% "Some of the time", 3,
                                        ifelse(SDOH_ss3$answer %in% "Most of the time", 4, 5))))
SDOH_ss3 <- as.data.table(SDOH_ss3)

SDOH_ss4 <- SDOH_survey[which(SDOH_survey$question_concept_id == 40192511), c("person_id", "answer")]
SDOH_ss4 <- SDOH_ss4[-which(SDOH_ss4$answer %in% "PMI: Skip"), ]
SDOH_ss4$answer <- ifelse(SDOH_ss4$answer %in% "None of the time", 1,
                          ifelse(SDOH_ss4$answer %in% "A little of the time", 2, 
                                 ifelse(SDOH_ss4$answer %in% "Some of the time", 3,
                                        ifelse(SDOH_ss4$answer %in% "Most of the time", 4, 5))))
SDOH_ss4 <- as.data.table(SDOH_ss4)

SDOH_ss5 <- SDOH_survey[which(SDOH_survey$question_concept_id == 40192439), c("person_id", "answer")]
SDOH_ss5 <- SDOH_ss5[-which(SDOH_ss5$answer %in% "PMI: Skip"), ]
SDOH_ss5$answer <- ifelse(SDOH_ss5$answer %in% "None of the time", 1,
                          ifelse(SDOH_ss5$answer %in% "A little of the time", 2, 
                                 ifelse(SDOH_ss5$answer %in% "Some of the time", 3,
                                        ifelse(SDOH_ss5$answer %in% "Most of the time", 4, 5))))
SDOH_ss5 <- as.data.table(SDOH_ss5)

SDOH_ss6 <- SDOH_survey[which(SDOH_survey$question_concept_id == 40192528), c("person_id", "answer")]
SDOH_ss6 <- SDOH_ss6[-which(SDOH_ss6$answer %in% "PMI: Skip"), ]
SDOH_ss6$answer <- ifelse(SDOH_ss6$answer %in% "None of the time", 1,
                          ifelse(SDOH_ss6$answer %in% "A little of the time", 2, 
                                 ifelse(SDOH_ss6$answer %in% "Some of the time", 3,
                                        ifelse(SDOH_ss6$answer %in% "Most of the time", 4, 5))))
SDOH_ss6 <- as.data.table(SDOH_ss6)

SDOH_ss7 <- SDOH_survey[which(SDOH_survey$question_concept_id == 40192399), c("person_id", "answer")]
SDOH_ss7 <- SDOH_ss7[-which(SDOH_ss7$answer %in% "PMI: Skip"), ]
SDOH_ss7$answer <- ifelse(SDOH_ss7$answer %in% "None of the time", 1,
                          ifelse(SDOH_ss7$answer %in% "A little of the time", 2, 
                                 ifelse(SDOH_ss7$answer %in% "Some of the time", 3,
                                        ifelse(SDOH_ss7$answer %in% "Most of the time", 4, 5))))
SDOH_ss7 <- as.data.table(SDOH_ss7)

SDOH_ss8 <- SDOH_survey[which(SDOH_survey$question_concept_id == 40192446), c("person_id", "answer")]
SDOH_ss8 <- SDOH_ss8[-which(SDOH_ss8$answer %in% "PMI: Skip"), ]
SDOH_ss8$answer <- ifelse(SDOH_ss8$answer %in% "None of the time", 1,
                          ifelse(SDOH_ss8$answer %in% "A little of the time", 2, 
                                 ifelse(SDOH_ss8$answer %in% "Some of the time", 3,
                                        ifelse(SDOH_ss8$answer %in% "Most of the time", 4, 5))))
SDOH_ss8 <- as.data.table(SDOH_ss8)

SDOH_ss12 <- SDOH_ss2[SDOH_ss1, on = "person_id"]
SDOH_ss123 <- SDOH_ss3[SDOH_ss12, on = "person_id"]
SDOH_ss1234 <- SDOH_ss4[SDOH_ss123, on = "person_id"]
SDOH_ss12345 <- SDOH_ss5[SDOH_ss1234, on = "person_id"]
SDOH_ss123456 <- SDOH_ss6[SDOH_ss12345, on = "person_id"]
SDOH_ss1234567 <- SDOH_ss7[SDOH_ss123456, on = "person_id"]
SDOH_ss12345678 <- SDOH_ss8[SDOH_ss1234567, on = "person_id"]
names(SDOH_ss12345678) <- c("person_id", "answer1", "answer2", "answer3", "answer4", "answer5", "answer6", "answer7", "answer8")
# Define the custom function
mean_if_at_least_6 <- function(x) {
  if (sum(!is.na(x)) >= 6) {
    return(mean(x, na.rm = TRUE))
  } else {
    return(NA)
  }
}

# Apply the function to each row
SDOH_ss12345678$answer <- apply(SDOH_ss12345678[, -1], 1, mean_if_at_least_6)
SDOH_ss <- SDOH_ss12345678[-which(is.na(SDOH_ss12345678$answer)), c("person_id", "answer")]
names(SDOH_ss) <- c("person_id", "ss")
SDOH_ss$ss <- ifelse(SDOH_ss$ss > 2, "Yes", "No")
SDOH_ss$ss <- as.factor(SDOH_ss$ss)
SDOH_ss <- as.data.table(SDOH_ss)
person_table1 <- SDOH_ss[person_table1, on = "person_id"]
# (numerical ss)
SDOH_ss12 <- SDOH_ss2[SDOH_ss1, on = "person_id"]
SDOH_ss123 <- SDOH_ss3[SDOH_ss12, on = "person_id"]
SDOH_ss1234 <- SDOH_ss4[SDOH_ss123, on = "person_id"]
SDOH_ss12345 <- SDOH_ss5[SDOH_ss1234, on = "person_id"]
SDOH_ss123456 <- SDOH_ss6[SDOH_ss12345, on = "person_id"]
SDOH_ss1234567 <- SDOH_ss7[SDOH_ss123456, on = "person_id"]
SDOH_ss12345678 <- SDOH_ss8[SDOH_ss1234567, on = "person_id"]
names(SDOH_ss12345678) <- c("person_id", "answer1", "answer2", "answer3", "answer4", "answer5", "answer6", "answer7", "answer8")
# Apply the function to each row
SDOH_ss12345678$answer <- apply(SDOH_ss12345678[, -1], 1, mean_if_at_least_6)
SDOH_ss <- SDOH_ss12345678[-which(is.na(SDOH_ss12345678$answer)), c("person_id", "answer")]
names(SDOH_ss) <- c("person_id", "ss")
SDOH_ss <- as.data.table(SDOH_ss)
person_figure2 <- SDOH_ss[person_figure2, on = "person_id"]

# Housing quality - 1 item (Bug infestation, Mold, Lead paint or pipes, inadequate heat, oven or stove not working, no or not working smoke detector, water leaks, non oe fthe above)
# 40192402 Think about the place you live. Do you have problems with any of the following? Select all that apply. 
SDOH_hq <- SDOH_survey[which(SDOH_survey$question_concept_id == 40192402), c("person_id", "answer")]
SDOH_hq <- SDOH_hq[-which(SDOH_hq$answer %in% "PMI: Skip"), ]
SDOH_hq$answer <- ifelse(SDOH_hq$answer %in% "None of the above", "No", "Yes")
SDOH_hq <- SDOH_hq %>% distinct()
SDOH_hq$answer <- as.factor(SDOH_hq$answer)
names(SDOH_hq) <- c("person_id", "hq")
SDOH_hq <- as.data.table(SDOH_hq)
person_table1 <- SDOH_hq[person_table1, on = "person_id"]
person_figure2 <- SDOH_hq[person_figure2, on = "person_id"]

# Social cohesion neighborhood - 4 items (Strongly agree 1, Agree 2, Neutral 3, Disagree 4, Strongly disagree 5)
# 40192463 How much you agree or disagree that people around here are willing to help their neighbor?
# 40192411 How much you agree or disagree that people in your neighborhood generally get along with each other?
# 40192499 How much you agree or disagree that people in your neighborhood can be trusted?
# 40192417 How much you agree or disagree that people in your neighborhood share the same values?
# Caculate as missing if any of the 4 items is missing
SDOH_scns1 <- SDOH_survey[which(SDOH_survey$question_concept_id == 40192463), c("person_id", "answer")]
SDOH_scns1 <- SDOH_scns1[-which(SDOH_scns1$answer %in% "PMI: Skip"), ]
SDOH_scns1$answer <- ifelse(SDOH_scns1$answer %in% "Strongly agree", 1,
                           ifelse(SDOH_scns1$answer %in% "Agree", 2, 
                                  ifelse(SDOH_scns1$answer %in% "Neutral (neither agree nor disagree)", 3,
                                         ifelse(SDOH_scns1$answer %in% "Disagree", 4, 5))))
SDOH_scns1 <- as.data.table(SDOH_scns1)

SDOH_scns2 <- SDOH_survey[which(SDOH_survey$question_concept_id == 40192411), c("person_id", "answer")]
SDOH_scns2 <- SDOH_scns2[-which(SDOH_scns2$answer %in% "PMI: Skip"), ]
SDOH_scns2$answer <- ifelse(SDOH_scns2$answer %in% "Strongly agree", 1,
                            ifelse(SDOH_scns2$answer %in% "Agree", 2, 
                                   ifelse(SDOH_scns2$answer %in% "Neutral (neither agree nor disagree)", 3,
                                          ifelse(SDOH_scns2$answer %in% "Disagree", 4, 5))))
SDOH_scns2 <- as.data.table(SDOH_scns2)

SDOH_scns3 <- SDOH_survey[which(SDOH_survey$question_concept_id == 40192499), c("person_id", "answer")]
SDOH_scns3 <- SDOH_scns3[-which(SDOH_scns3$answer %in% "PMI: Skip"), ]
SDOH_scns3$answer <- ifelse(SDOH_scns3$answer %in% "Strongly agree", 1,
                            ifelse(SDOH_scns3$answer %in% "Agree", 2, 
                                   ifelse(SDOH_scns3$answer %in% "Neutral (neither agree nor disagree)", 3,
                                          ifelse(SDOH_scns3$answer %in% "Disagree", 4, 5))))
SDOH_scns3 <- as.data.table(SDOH_scns3)

SDOH_scns4 <- SDOH_survey[which(SDOH_survey$question_concept_id == 40192417), c("person_id", "answer")]
SDOH_scns4 <- SDOH_scns4[-which(SDOH_scns4$answer %in% "PMI: Skip"), ]
SDOH_scns4$answer <- ifelse(SDOH_scns4$answer %in% "Strongly agree", 1,
                            ifelse(SDOH_scns4$answer %in% "Agree", 2, 
                                   ifelse(SDOH_scns4$answer %in% "Neutral (neither agree nor disagree)", 3,
                                          ifelse(SDOH_scns4$answer %in% "Disagree", 4, 5))))
SDOH_scns4 <- as.data.table(SDOH_scns4)

SDOH_scns12 <- SDOH_scns2[SDOH_scns1, on = "person_id"]
SDOH_scns123 <- SDOH_scns3[SDOH_scns12, on = "person_id"]
SDOH_scns1234 <- SDOH_scns4[SDOH_scns123, on = "person_id"]
names(SDOH_scns1234) <- c("person_id", "answer1", "answer2", "answer3", "answer4")
SDOH_scns1234$answer <- SDOH_scns1234$answer1 + SDOH_scns1234$answer2 + SDOH_scns1234$answer3 + SDOH_scns1234$answer4 
SDOH_scns <- SDOH_scns1234[-which(is.na(SDOH_scns1234$answer)), c("person_id", "answer")]
SDOH_scns$answer <- SDOH_scns$answer/4
names(SDOH_scns) <- c("person_id", "scns")
SDOH_scns$scns <- ifelse(SDOH_scns$scns > 3, "Yes", "No")
SDOH_scns$scns <- as.factor(SDOH_scns$scns)
SDOH_scns <- as.data.table(SDOH_scns)
person_table1 <- SDOH_scns[person_table1, on = "person_id"]
# (numerical ps)
SDOH_scns12 <- SDOH_scns2[SDOH_scns1, on = "person_id"]
SDOH_scns123 <- SDOH_scns3[SDOH_scns12, on = "person_id"]
SDOH_scns1234 <- SDOH_scns4[SDOH_scns123, on = "person_id"]
names(SDOH_scns1234) <- c("person_id", "answer1", "answer2", "answer3", "answer4")
SDOH_scns1234$answer <- SDOH_scns1234$answer1 + SDOH_scns1234$answer2 + SDOH_scns1234$answer3 + SDOH_scns1234$answer4 
SDOH_scns <- SDOH_scns1234[-which(is.na(SDOH_scns1234$answer)), c("person_id", "answer")]
SDOH_scns$answer <- SDOH_scns$answer/4
names(SDOH_scns) <- c("person_id", "scns")
SDOH_scns <- as.data.table(SDOH_scns)
person_figure2 <- SDOH_scns[person_figure2, on = "person_id"]
```

```{r}
################################################################################
#                                 2023/09/20 update                            #
################################################################################

Figure1_fun <- function(data){
  options(digits = 10)
  data_Table1 <- data
  data_Table1_merge <- person_table1[data_Table1, on = "person_id"]
    
  # Age
  ageCat1_data <- data_Table1_merge[which(data_Table1_merge$age_cat == 1),]
  mod_ageCat1 <- lm(ageCat1_data$nMatch ~ 1)
  ageCat1 <- c(coefficients(mod_ageCat1)[[1]], confint(mod_ageCat1)[[1]], confint(mod_ageCat1)[[2]])
  ageCat2_data <- data_Table1_merge[which(data_Table1_merge$age_cat == 2),]
  mod_ageCat2 <- lm(ageCat2_data$nMatch ~ 1)
  ageCat2 <- c(coefficients(mod_ageCat2)[[1]], confint(mod_ageCat2)[[1]], confint(mod_ageCat2)[[2]])

  # Sex
  female_data <- data_Table1_merge[which(data_Table1_merge$sex_at_birth %in% "Female"),]
  mod_female <- lm(female_data$nMatch ~ 1)
  female <- c(coefficients(mod_female)[[1]], confint(mod_female)[[1]], confint(mod_female)[[2]])
  male_data <- data_Table1_merge[which(data_Table1_merge$sex_at_birth %in% "Male"),]
  mod_male <- lm(male_data$nMatch ~ 1)
  male <- c(coefficients(mod_male)[[1]], confint(mod_male)[[1]], confint(mod_male)[[2]])
  intersex_data <- data_Table1_merge[which(data_Table1_merge$sex_at_birth %in% "Intersex"),]
  mod_intersex <- lm(intersex_data$nMatch ~ 1)
  intersex <- c(coefficients(mod_intersex)[[1]], confint(mod_intersex)[[1]], confint(mod_intersex)[[2]])

  # R/E
  White_data <- data_Table1_merge[which(data_Table1_merge$race_ethnicity %in% "White"),]
  mod_White <- lm(White_data$nMatch ~ 1)
  White <- c(coefficients(mod_White)[[1]], confint(mod_White)[[1]], confint(mod_White)[[2]])
  Black_data <- data_Table1_merge[which(data_Table1_merge$race_ethnicity %in% "Black"),]
  mod_Black <- lm(Black_data$nMatch ~ 1)
  Black <- c(coefficients(mod_Black)[[1]], confint(mod_Black)[[1]], confint(mod_Black)[[2]])
  Hispanic_data <- data_Table1_merge[which(data_Table1_merge$race_ethnicity %in% "Hispanic"),]
  mod_Hispanic <- lm(Hispanic_data$nMatch ~ 1)
  Hispanic <- c(coefficients(mod_Hispanic)[[1]], confint(mod_Hispanic)[[1]], confint(mod_Hispanic)[[2]])
  Asian_data <- data_Table1_merge[which(data_Table1_merge$race_ethnicity %in% "Asian"),]
  mod_Asian <- lm(Asian_data$nMatch ~ 1)
  Asian <- c(coefficients(mod_Asian)[[1]], confint(mod_Asian)[[1]], confint(mod_Asian)[[2]])
  MENA_data <- data_Table1_merge[which(data_Table1_merge$race_ethnicity %in% "MENA"),]
  mod_MENA <- lm(MENA_data$nMatch ~ 1)
  MENA <- c(coefficients(mod_MENA)[[1]], confint(mod_MENA)[[1]], confint(mod_MENA)[[2]])
  NHOPI_data <- data_Table1_merge[which(data_Table1_merge$race_ethnicity %in% "NHOPI"),]
  mod_NHOPI <- lm(NHOPI_data$nMatch ~ 1)
  NHOPI <- c(coefficients(mod_NHOPI)[[1]], confint(mod_NHOPI)[[1]], confint(mod_NHOPI)[[2]])
  Multiple_data <- data_Table1_merge[which(data_Table1_merge$race_ethnicity %in% "Multiple"),]
  mod_Multiple <- lm(Multiple_data$nMatch ~ 1)
  Multiple <- c(coefficients(mod_Multiple)[[1]], confint(mod_Multiple)[[1]], confint(mod_Multiple)[[2]])
  Other_data <- data_Table1_merge[which(data_Table1_merge$race_ethnicity %in% "Other"),]
  mod_Other <- lm(Other_data$nMatch ~ 1)
  Other <- c(coefficients(mod_Other)[[1]], confint(mod_Other)[[1]], confint(mod_Other)[[2]])
 
  # Education
  Eleven_below_data <- data_Table1_merge[which(data_Table1_merge$education %in% c("Eleven or below")), ]
  mod_Eleven_below <- lm(Eleven_below_data$nMatch ~ 1)
  Eleven_below <- c(coefficients(mod_Eleven_below)[[1]], confint(mod_Eleven_below)[[1]], confint(mod_Eleven_below)[[2]])

  Twelve_GED_data <- data_Table1_merge[which(data_Table1_merge$education %in% c("Twelve or GED")), ]
  mod_Twelve_GED <- lm(Twelve_GED_data$nMatch ~ 1)
  Twelve_GED <- c(coefficients(mod_Twelve_GED)[[1]], confint(mod_Twelve_GED)[[1]], confint(mod_Twelve_GED)[[2]])

  College_graduate_data <- data_Table1_merge[which(data_Table1_merge$education %in% c("College Graduate")), ]
  mod_College_graduate <- lm(College_graduate_data$nMatch ~ 1)
  College_graduate <- c(coefficients(mod_College_graduate)[[1]], confint(mod_College_graduate)[[1]], confint(mod_College_graduate)[[2]])

  Advanced_degree_data <- data_Table1_merge[which(data_Table1_merge$education %in% c("Advanced Degree")), ]
  mod_Advanced_degree <- lm(Advanced_degree_data$nMatch ~ 1)
  Advanced_degree <- c(coefficients(mod_Advanced_degree)[[1]], confint(mod_Advanced_degree)[[1]], confint(mod_Advanced_degree)[[2]])
    
  # Location
  Metro_data <- data_Table1_merge[which(data_Table1_merge$location %in% "Metro"),]
  mod_Metro <- lm(Metro_data$nMatch ~ 1)
  Metro <- c(coefficients(mod_Metro)[[1]], confint(mod_Metro)[[1]], confint(mod_Metro)[[2]])
  NonMetro_data <- data_Table1_merge[which(data_Table1_merge$location %in% "NonMetro"),]
  mod_NonMetro <- lm(NonMetro_data$nMatch ~ 1)
  NonMetro <- c(coefficients(mod_NonMetro)[[1]], confint(mod_NonMetro)[[1]], confint(mod_NonMetro)[[2]])

  # Income
  low_income_data_yes <- data_Table1_merge[which(data_Table1_merge$low_income %in% "Yes"),]
  mod_low_income_yes <- lm(low_income_data_yes$nMatch ~ 1)
  low_income_yes <- c(coefficients(mod_low_income_yes)[[1]], confint(mod_low_income_yes)[[1]], confint(mod_low_income_yes)[[2]])

  low_income_data_no <- data_Table1_merge[which(data_Table1_merge$low_income %in% "No"),]
  mod_low_income_no <- lm(low_income_data_no$nMatch ~ 1)
  low_income_no <- c(coefficients(mod_low_income_no)[[1]], confint(mod_low_income_no)[[1]], confint(mod_low_income_no)[[2]])
    
 # Disability
  disability_data_yes <- data_Table1_merge[which(data_Table1_merge$any_disability %in% "Yes"),]
  mod_disability_yes <- lm(disability_data_yes$nMatch ~ 1)
  disability_yes <- c(coefficients(mod_disability_yes)[[1]], confint(mod_disability_yes)[[1]], confint(mod_disability_yes)[[2]])

  disability_data_no <- data_Table1_merge[which(data_Table1_merge$any_disability %in% "No"),]
  mod_disability_no <- lm(disability_data_no$nMatch ~ 1)
  disability_no <- c(coefficients(mod_disability_no)[[1]], confint(mod_disability_no)[[1]], confint(mod_disability_no)[[2]])

  # English proficiency
  EngProf_data_yes <- data_Table1_merge[which(data_Table1_merge$EngProf %in% "Yes"),]
  mod_EngProf_yes <- lm(EngProf_data_yes$nMatch ~ 1)
  EngProf_yes <- c(coefficients(mod_EngProf_yes)[[1]], confint(mod_EngProf_yes)[[1]], confint(mod_EngProf_yes)[[2]])

  EngProf_data_no <- data_Table1_merge[which(data_Table1_merge$EngProf %in% "No"),]
  mod_EngProf_no <- lm(EngProf_data_no$nMatch ~ 1)
  EngProf_no <- c(coefficients(mod_EngProf_no)[[1]], confint(mod_EngProf_no)[[1]], confint(mod_EngProf_no)[[2]])  
  
  # Food insecurity
  FI_data_yes <- data_Table1_merge[which(data_Table1_merge$FI %in% "Yes"),]
  mod_FI_yes <- lm(FI_data_yes$nMatch ~ 1)
  FI_yes <- c(coefficients(mod_FI_yes)[[1]], confint(mod_FI_yes)[[1]], confint(mod_FI_yes)[[2]])
    
  FI_data_no <- data_Table1_merge[which(data_Table1_merge$FI %in% "No"),]
  mod_FI_no <- lm(FI_data_no$nMatch ~ 1)
  FI_no <- c(coefficients(mod_FI_no)[[1]], confint(mod_FI_no)[[1]], confint(mod_FI_no)[[2]])
    
  # Housing instability
  HI_data_yes <- data_Table1_merge[which(data_Table1_merge$HousingInstability %in% "Yes"), ]
  mod_HI_yes <- lm(HI_data_yes$nMatch ~ 1)
  HI_yes <- c(coefficients(mod_HI_yes)[[1]], confint(mod_HI_yes)[[1]], confint(mod_HI_yes)[[2]])
    
  HI_data_no <- data_Table1_merge[which(data_Table1_merge$HousingInstability %in% "No"), ]
  mod_HI_no <- lm(HI_data_no$nMatch ~ 1)
  HI_no <- c(coefficients(mod_HI_no)[[1]], confint(mod_HI_no)[[1]], confint(mod_HI_no)[[2]])
    
  # Everyday discrimination
  eds_data_yes <- data_Table1_merge[which(data_Table1_merge$eds %in% "Yes"), ]
  mod_eds_yes <- lm(eds_data_yes$nMatch ~ 1)
  eds_yes <- c(coefficients(mod_eds_yes)[[1]], confint(mod_eds_yes)[[1]], confint(mod_eds_yes)[[2]])

  eds_data_no <- data_Table1_merge[which(data_Table1_merge$eds %in% "No"), ]
  mod_eds_no <- lm(eds_data_no$nMatch ~ 1)
  eds_no <- c(coefficients(mod_eds_no)[[1]], confint(mod_eds_no)[[1]], confint(mod_eds_no)[[2]])

  # Social support
  ss_data_yes <- data_Table1_merge[which(data_Table1_merge$ss %in% "Yes"), ]
  mod_ss_yes <- lm(ss_data_yes$nMatch ~ 1)
  ss_yes <- c(coefficients(mod_ss_yes)[[1]], confint(mod_ss_yes)[[1]], confint(mod_ss_yes)[[2]])

  ss_data_no <- data_Table1_merge[which(data_Table1_merge$ss %in% "No"), ]
  mod_ss_no <- lm(ss_data_no$nMatch ~ 1)
  ss_no <- c(coefficients(mod_ss_no)[[1]], confint(mod_ss_no)[[1]], confint(mod_ss_no)[[2]])
    
  # Neighborhood disorder
  hq_data_yes <- data_Table1_merge[which(data_Table1_merge$hq %in% "Yes"), ]
  mod_hq_yes <- lm(hq_data_yes$nMatch ~ 1)
  hq_yes <- c(coefficients(mod_hq_yes)[[1]], confint(mod_hq_yes)[[1]], confint(mod_hq_yes)[[2]])

  hq_data_no <- data_Table1_merge[which(data_Table1_merge$hq %in% "No"), ]
  mod_hq_no <- lm(hq_data_no$nMatch ~ 1)
  hq_no <- c(coefficients(mod_hq_no)[[1]], confint(mod_hq_no)[[1]], confint(mod_hq_no)[[2]])
  
  # Social cohesion neighborhood
  scns_data_yes <- data_Table1_merge[which(data_Table1_merge$scns %in% "Yes"), ]
  mod_scns_yes <- lm(scns_data_yes$nMatch ~ 1)
  scns_yes <- c(coefficients(mod_scns_yes)[[1]], confint(mod_scns_yes)[[1]], confint(mod_scns_yes)[[2]])
  
  scns_data_no <- data_Table1_merge[which(data_Table1_merge$scns %in% "No"), ]
  mod_scns_no <- lm(scns_data_no$nMatch ~ 1)
  scns_no <- c(coefficients(mod_scns_no)[[1]], confint(mod_scns_no)[[1]], confint(mod_scns_no)[[2]])

return(data.frame(ageCat1, ageCat2, male, female, intersex, White, Black, Hispanic, Asian, MENA, 
                  NHOPI, Multiple, Other, Metro, NonMetro, EngProf_yes, EngProf_no, FI_yes, FI_no,
                  HI_yes, HI_no, low_income_yes, low_income_no, eds_yes, eds_no, ss_yes, ss_no,
                  Eleven_below, Twelve_GED, College_graduate, Advanced_degree, hq_yes, hq_no, scns_yes, scns_no,
                 disability_yes, disability_no))
}


# other_Table1 <- Table1_fun(data = AoU_to_CTgov_wZip_Trial_other)
other_Figure1 <- Figure1_fun(data = AoU_to_CTgov_wZip_Trial_other)
other_Fig1 <- as.data.frame(t(other_Figure1))

# respiratory_Table1 <- Table1_fun(data = AoU_to_CTgov_wZip_Trial_respiratory)
respiratory_Figure1 <- Figure1_fun(data = AoU_to_CTgov_wZip_Trial_respiratory)
respiratory_Fig1 <- as.data.frame(t(respiratory_Figure1))

# circulatory_Table1 <- Table1_fun(data = AoU_to_CTgov_wZip_Trial_circulatory)
circulatory_Figure1 <- Figure1_fun(data = AoU_to_CTgov_wZip_Trial_circulatory)
circulatory_Fig1 <- as.data.frame(t(circulatory_Figure1))

# neurological_Table1 <- Table1_fun(data = AoU_to_CTgov_wZip_Trial_neurological)
neurological_Figure1 <- Figure1_fun(data = AoU_to_CTgov_wZip_Trial_neurological)
neurological_Fig1 <- as.data.frame(t(neurological_Figure1))

# em_Table1 <- Table1_fun(data = AoU_to_CTgov_wZip_Trial_em)
em_Figure1 <- Figure1_fun(data = AoU_to_CTgov_wZip_Trial_em)
em_Fig1 <- as.data.frame(t(em_Figure1))

# mental_Table1 <- Table1_fun(data = AoU_to_CTgov_wZip_Trial_mental)
mental_Figure1 <- Figure1_fun(data = AoU_to_CTgov_wZip_Trial_mental)
mental_Fig1 <- as.data.frame(t(mental_Figure1))

# neoplasms_Table1 <- Table1_fun(data = AoU_to_CTgov_wZip_Trial_neoplasms)
neoplasms_Figure1 <- Figure1_fun(data = AoU_to_CTgov_wZip_Trial_neoplasms)
neoplasms_Fig1 <- as.data.frame(t(neoplasms_Figure1))

# overall_Table1 <- Table1_fun(data = AoU_to_CTgov_wZip_Trial_overall)
overall_Figure1 <- Figure1_fun(data = AoU_to_CTgov_wZip_Trial_overall)
Overall_Fig1 <- as.data.frame(t(overall_Figure1))

# Overall avg and 95% CI
data_Table1 <- fread("AoU_to_CTgov_wZip_Trial.csv", header = TRUE)
data_Table1_merge <- person_table1[data_Table1, on = "person_id"]
mod_Overall <- lm(data_Table1_merge$nMatch ~ 1)
Overall <- c(coefficients(mod_Overall)[[1]], confint(mod_Overall)[[1]], confint(mod_Overall)[[2]]) 

# RE minorities only
RE_data_Table1_merge <- data_Table1_merge[!which(data_Table1_merge$race_ethnicity %in% "White"), ]
mod_RE_minorities <- lm(RE_data_Table1_merge$nMatch ~ 1)
RE_minorities <- c(coefficients(mod_RE_minorities)[[1]], confint(mod_RE_minorities)[[1]], confint(mod_RE_minorities)[[2]]) 
```

```{r}
################################################################################
#                                 2023/12/02 update                            #
################################################################################
################################################################################
#                                    Figure 5                                  #
################################################################################
person_figure2$low_income <- factor(person_figure2$low_income, levels = c("No", "Yes"))
# person_figure2$max_income <- factor(person_figure2$max_income, levels = c("9999", "25000", "35000", "50000", "75000", "100000", "150000", "200000", "200001"))
person_figure2$EngProf <- factor(person_figure2$EngProf, levels = c("No", "Yes"))
person_figure2$education <- factor(person_figure2$education, levels = c("Eleven or below", "Twelve or GED", "College Graduate", "Advanced Degree"))
#person_figure2$education <- ifelse(person_figure2$education %in% "Eleven or below", "Eleven or below", "Twelve or above")
#person_figure2$education <- factor(person_figure2$education, levels = c("Eleven or below", "Twelve or above"))
person_figure2$location <- factor(person_figure2$location, levels = c("Metro", "NonMetro"))
person_figure2$race_ethnicity <- factor(person_figure2$race_ethnicity, levels = c("White", "Black", "Hispanic", "Asian", "MENA", "NHOPI", "Multiple", "Other"))
person_figure2$sex_at_birth <- factor(person_figure2$sex_at_birth, levels = c("Female", "Male", "Intersex"))

# eds - Higher = worse
# ss - Lower = better
# scns - Higher = worse
# Housing instability - Higher = worse
Figure2_fun <- function(data, data_nCond){
  data_Table1 <- data
  data_Table1_merge <- person_figure2[data_Table1, on = "person_id"]
  data_Table1_merge2 <- data_nCond[data_Table1_merge, on = "person_id"]
  mod <- glm.nb(nMatch ~ n_condition + sex_at_birth + age_in_years + location + race_ethnicity + education + low_income + scns + ss + hq + EngProf + eds + FI, data = data_Table1_merge2)
  # return(data.frame(coef = coefficients(mod), confint(mod), pval = coef(summary(mod))[, 4]))
  return(summary(mod))
}

Figure2_neoplasms <- Figure2_fun(data = AoU_to_CTgov_wZip_Trial_neoplasms, person_nCond_neoplasms)
# Figure2_neoplasms
write.csv(Figure2_neoplasms, file = "Figure2_neoplasms.csv")
Figure2_em <- Figure2_fun(data = AoU_to_CTgov_wZip_Trial_em, person_nCond_em)
# Figure2_em
write.csv(Figure2_em, file = "Figure2_em.csv")
Figure2_circulatory <- Figure2_fun(data = AoU_to_CTgov_wZip_Trial_circulatory, person_nCond_circulatory)
# Figure2_circulatory
write.csv(Figure2_circulatory, file = "Figure2_circulatory.csv")
Figure2_respiratory <- Figure2_fun(data = AoU_to_CTgov_wZip_Trial_respiratory, person_nCond_respiratory)
# Figure2_respiratory
write.csv(Figure2_respiratory, file = "Figure2_respiratory.csv")
Figure2_mental <- Figure2_fun(data = AoU_to_CTgov_wZip_Trial_mental, person_nCond_mental)
# Figure2_respiratory
write.csv(Figure2_mental, file = "Figure2_mental.csv")
Figure2_other <- Figure2_fun(data = AoU_to_CTgov_wZip_Trial_other, person_nCond_other)
# Figure2_other
write.csv(Figure2_other, file = "Figure2_other.csv")
Figure2_neurological <- Figure2_fun(data = AoU_to_CTgov_wZip_Trial_neurological, person_nCond_neurological)
# Figure2_neurological
write.csv(Figure2_neurological, file = "Figure2_neurological.csv")
```


```{r}
####################################################################################################
#                                            Table 1                                               #
####################################################################################################
#########################################
#                Other                  #
#########################################
# For each participant, count the number of studies s/he matches with
AoU_to_CTgov_wZip_Trial_other <- trial_dat_expanded_zip[person_condition_df_phecode_phenotype_other, on = c("Phecode", "sex_at_birth_concept_id", "zip", "MaximumAge >= age_in_years", "MinimumAge <= age_in_years"), .(list(NCTId)), by = .EACHI]
AoU_to_CTgov_wZip_Trial_other$person_id <- person_condition_df_phecode_phenotype_other$person_id
AoU_to_CTgov_wZip_Trial_ReturnOfValue_other <- AoU_to_CTgov_wZip_Trial_other
AoU_to_CTgov_wZip_Trial_ReturnOfValue_other <- AoU_to_CTgov_wZip_Trial_ReturnOfValue_other[, c("person_id", "V1", "Phecode")]
AoU_to_CTgov_wZip_Trial_other <- AoU_to_CTgov_wZip_Trial_other[, .(nMatch = uniqueN(unlist(V1), na.rm = TRUE)), by = .(person_id)]
write.csv(AoU_to_CTgov_wZip_Trial_other, file = "AoU_to_CTgov_wZip_Trial_other.csv")
AoU_to_CTgov_wZip_Trial_other <- AoU_to_CTgov_wZip_Trial_other[order(AoU_to_CTgov_wZip_Trial_other$nMatch, decreasing = TRUE), ]

#########################################
#                infectious             #
#########################################
# For each participant, count the number of studies s/he matches with
AoU_to_CTgov_wZip_Trial_infectious <- trial_dat_expanded_zip[person_condition_df_phecode_phenotype_infectious, on = c("Phecode", "sex_at_birth_concept_id", "zip", "MaximumAge >= age_in_years", "MinimumAge <= age_in_years"), .(list(NCTId)), by = .EACHI]
AoU_to_CTgov_wZip_Trial_infectious$person_id <- person_condition_df_phecode_phenotype_infectious$person_id
AoU_to_CTgov_wZip_Trial_ReturnOfValue_infectious <- AoU_to_CTgov_wZip_Trial_infectious
AoU_to_CTgov_wZip_Trial_ReturnOfValue_infectious <- AoU_to_CTgov_wZip_Trial_ReturnOfValue_infectious[, c("person_id", "V1", "Phecode")]
AoU_to_CTgov_wZip_Trial_infectious <- AoU_to_CTgov_wZip_Trial_infectious[, .(nMatch = uniqueN(unlist(V1), na.rm = TRUE)), by = .(person_id)]
write.csv(AoU_to_CTgov_wZip_Trial_infectious, file = "AoU_to_CTgov_wZip_Trial_infectious.csv")
AoU_to_CTgov_wZip_Trial_infectious <- AoU_to_CTgov_wZip_Trial_infectious[order(AoU_to_CTgov_wZip_Trial_infectious$nMatch, decreasing = TRUE), ]

#########################################
#                neurological           #
#########################################
# For each participant, count the number of studies s/he matches with
AoU_to_CTgov_wZip_Trial_neurological <- trial_dat_expanded_zip[person_condition_df_phecode_phenotype_neurological, on = c("Phecode", "sex_at_birth_concept_id", "zip", "MaximumAge >= age_in_years", "MinimumAge <= age_in_years"), .(list(NCTId)), by = .EACHI]
AoU_to_CTgov_wZip_Trial_neurological$person_id <- person_condition_df_phecode_phenotype_neurological$person_id
AoU_to_CTgov_wZip_Trial_ReturnOfValue_neurological <- AoU_to_CTgov_wZip_Trial_neurological
AoU_to_CTgov_wZip_Trial_ReturnOfValue_neurological <- AoU_to_CTgov_wZip_Trial_ReturnOfValue_neurological[, c("person_id", "V1", "Phecode")]
AoU_to_CTgov_wZip_Trial_neurological <- AoU_to_CTgov_wZip_Trial_neurological[, .(nMatch = uniqueN(unlist(V1), na.rm = TRUE)), by = .(person_id)]
write.csv(AoU_to_CTgov_wZip_Trial_neurological, file = "AoU_to_CTgov_wZip_Trial_neurological.csv")
AoU_to_CTgov_wZip_Trial_neurological <- AoU_to_CTgov_wZip_Trial_neurological[order(AoU_to_CTgov_wZip_Trial_neurological$nMatch, decreasing = TRUE), ]

#########################################
#                circulatory            #
#########################################
# For each participant, count the number of studies s/he matches with
AoU_to_CTgov_wZip_Trial_circulatory <- trial_dat_expanded_zip[person_condition_df_phecode_phenotype_circulatory, on = c("Phecode", "sex_at_birth_concept_id", "zip", "MaximumAge >= age_in_years", "MinimumAge <= age_in_years"), .(list(NCTId)), by = .EACHI]
AoU_to_CTgov_wZip_Trial_circulatory$person_id <- person_condition_df_phecode_phenotype_circulatory$person_id
AoU_to_CTgov_wZip_Trial_ReturnOfValue_circulatory <- AoU_to_CTgov_wZip_Trial_circulatory
AoU_to_CTgov_wZip_Trial_ReturnOfValue_circulatory <- AoU_to_CTgov_wZip_Trial_ReturnOfValue_circulatory[, c("person_id", "V1", "Phecode")]
AoU_to_CTgov_wZip_Trial_circulatory <- AoU_to_CTgov_wZip_Trial_circulatory[, .(nMatch = uniqueN(unlist(V1), na.rm = TRUE)), by = .(person_id)]
write.csv(AoU_to_CTgov_wZip_Trial_circulatory, file = "AoU_to_CTgov_wZip_Trial_circulatory.csv")
AoU_to_CTgov_wZip_Trial_circulatory <- AoU_to_CTgov_wZip_Trial_circulatory[order(AoU_to_CTgov_wZip_Trial_circulatory$nMatch, decreasing = TRUE), ]

#########################################
#                respiratory            #
#########################################
# For each participant, count the number of studies s/he matches with
AoU_to_CTgov_wZip_Trial_respiratory <- trial_dat_expanded_zip[person_condition_df_phecode_phenotype_respiratory, on = c("Phecode", "sex_at_birth_concept_id", "zip", "MaximumAge >= age_in_years", "MinimumAge <= age_in_years"), .(list(NCTId)), by = .EACHI]
AoU_to_CTgov_wZip_Trial_respiratory$person_id <- person_condition_df_phecode_phenotype_respiratory$person_id
AoU_to_CTgov_wZip_Trial_ReturnOfValue_respiratory <- AoU_to_CTgov_wZip_Trial_respiratory
AoU_to_CTgov_wZip_Trial_ReturnOfValue_respiratory <- AoU_to_CTgov_wZip_Trial_ReturnOfValue_respiratory[, c("person_id", "V1", "Phecode")]
AoU_to_CTgov_wZip_Trial_respiratory <- AoU_to_CTgov_wZip_Trial_respiratory[, .(nMatch = uniqueN(unlist(V1), na.rm = TRUE)), by = .(person_id)]
write.csv(AoU_to_CTgov_wZip_Trial_respiratory, file = "AoU_to_CTgov_wZip_Trial_respiratory.csv")
AoU_to_CTgov_wZip_Trial_respiratory <- AoU_to_CTgov_wZip_Trial_respiratory[order(AoU_to_CTgov_wZip_Trial_respiratory$nMatch, decreasing = TRUE), ]

#########################################
#                mental                 #
#########################################
# For each participant, count the number of studies s/he matches with
AoU_to_CTgov_wZip_Trial_mental <- trial_dat_expanded_zip[person_condition_df_phecode_phenotype_mental, on = c("Phecode", "sex_at_birth_concept_id", "zip", "MaximumAge >= age_in_years", "MinimumAge <= age_in_years"), .(list(NCTId)), by = .EACHI]
AoU_to_CTgov_wZip_Trial_mental$person_id <- person_condition_df_phecode_phenotype_mental$person_id
AoU_to_CTgov_wZip_Trial_ReturnOfValue_mental <- AoU_to_CTgov_wZip_Trial_mental
AoU_to_CTgov_wZip_Trial_ReturnOfValue_mental <- AoU_to_CTgov_wZip_Trial_ReturnOfValue_mental[, c("person_id", "V1", "Phecode")]
AoU_to_CTgov_wZip_Trial_mental <- AoU_to_CTgov_wZip_Trial_mental[, .(nMatch = uniqueN(unlist(V1), na.rm = TRUE)), by = .(person_id)]
write.csv(AoU_to_CTgov_wZip_Trial_mental, file = "AoU_to_CTgov_wZip_Trial_mental.csv")
AoU_to_CTgov_wZip_Trial_mental <- AoU_to_CTgov_wZip_Trial_mental[order(AoU_to_CTgov_wZip_Trial_mental$nMatch, decreasing = TRUE), ]

#########################################
#                neoplasms              #
#########################################
# For each participant, count the number of studies s/he matches with
AoU_to_CTgov_wZip_Trial_neoplasms <- trial_dat_expanded_zip[person_condition_df_phecode_phenotype_neoplasms, on = c("Phecode", "sex_at_birth_concept_id", "zip", "MaximumAge >= age_in_years", "MinimumAge <= age_in_years"), .(list(NCTId)), by = .EACHI]
AoU_to_CTgov_wZip_Trial_neoplasms$person_id <- person_condition_df_phecode_phenotype_neoplasms$person_id
AoU_to_CTgov_wZip_Trial_ReturnOfValue_neoplasms <- AoU_to_CTgov_wZip_Trial_neoplasms
AoU_to_CTgov_wZip_Trial_ReturnOfValue_neoplasms <- AoU_to_CTgov_wZip_Trial_ReturnOfValue_neoplasms[, c("person_id", "V1", "Phecode")]
AoU_to_CTgov_wZip_Trial_neoplasms <- AoU_to_CTgov_wZip_Trial_neoplasms[, .(nMatch = uniqueN(unlist(V1), na.rm = TRUE)), by = .(person_id)]
write.csv(AoU_to_CTgov_wZip_Trial_neoplasms, file = "AoU_to_CTgov_wZip_Trial_neoplasms.csv")
AoU_to_CTgov_wZip_Trial_neoplasms <- AoU_to_CTgov_wZip_Trial_neoplasms[order(AoU_to_CTgov_wZip_Trial_neoplasms$nMatch, decreasing = TRUE), ]

############################################
#              endocrine/metabolic         #
############################################
# For each participant, count the number of studies s/he matches with
AoU_to_CTgov_wZip_Trial_em <- trial_dat_expanded_zip[person_condition_df_phecode_phenotype_em, on = c("Phecode", "sex_at_birth_concept_id", "zip", "MaximumAge >= age_in_years", "MinimumAge <= age_in_years"), .(list(NCTId)), by = .EACHI]
AoU_to_CTgov_wZip_Trial_em$person_id <- person_condition_df_phecode_phenotype_em$person_id
AoU_to_CTgov_wZip_Trial_ReturnOfValue_em <- AoU_to_CTgov_wZip_Trial_em
AoU_to_CTgov_wZip_Trial_ReturnOfValue_em <- AoU_to_CTgov_wZip_Trial_ReturnOfValue_em[, c("person_id", "V1", "Phecode")]
AoU_to_CTgov_wZip_Trial_em <- AoU_to_CTgov_wZip_Trial_em[, .(nMatch = uniqueN(unlist(V1), na.rm = TRUE)), by = .(person_id)]
write.csv(AoU_to_CTgov_wZip_Trial_em, file = "AoU_to_CTgov_wZip_Trial_em.csv")
AoU_to_CTgov_wZip_Trial_em <- AoU_to_CTgov_wZip_Trial_em[order(AoU_to_CTgov_wZip_Trial_em$nMatch, decreasing = TRUE), ]

##############################################################################################
#                                 (Add Race/Ethnicity)                                       #
##############################################################################################
person_condition_df_phecode_phenotype <- as.data.table(fread("person_condition_df_phecode_phenotype.csv", header = TRUE))
person_condition_df_phecode_phenotype <- person_condition_df_phecode_phenotype[, c("person_id", "sex_at_birth_concept_id", "age_in_years", "PheCode", "value_as_string", "race_concept_id", "ethnicity_concept_id")]
names(person_condition_df_phecode_phenotype) <- c("person_id", "sex_at_birth_concept_id", "age_in_years", "Phecode", "value_as_string", "race", "ethnicity")

person_condition_df_phecode_phenotype$zip <- sub("^.*([0-9]{3}).*", "\\1", person_condition_df_phecode_phenotype$value_as_string)
# Remove rows with invalid zip (000)
person_condition_df_phecode_phenotype <- person_condition_df_phecode_phenotype[-which(person_condition_df_phecode_phenotype$zip %in% "000"), ]
person_condition_df_phecode_phenotype <- person_condition_df_phecode_phenotype[, c("person_id", "sex_at_birth_concept_id", "age_in_years", "Phecode", "zip", "race", "ethnicity")]
person_condition_df_phecode_phenotype$race_ethnicity <- ifelse(person_condition_df_phecode_phenotype$race == 8527 & person_condition_df_phecode_phenotype$ethnicity == 38003564, "White",
                                                              ifelse(person_condition_df_phecode_phenotype$race == 8516 & person_condition_df_phecode_phenotype$ethnicity == 38003564, "Black",
                                                                    ifelse(person_condition_df_phecode_phenotype$race == 8515 & person_condition_df_phecode_phenotype$ethnicity == 38003564, "Asian",
                                                                          ifelse(person_condition_df_phecode_phenotype$race == 8557 & person_condition_df_phecode_phenotype$ethnicity == 38003564, "NHOPI",
                                                                                ifelse(person_condition_df_phecode_phenotype$race == 38003615 & person_condition_df_phecode_phenotype$ethnicity == 38003564, "MENA",
                                                                                       ifelse(person_condition_df_phecode_phenotype$race == 2000000008 & person_condition_df_phecode_phenotype$ethnicity == 38003564, "Multiple",
                                                                                              ifelse(person_condition_df_phecode_phenotype$ethnicity == 38003563, "Hispanic", "Other")))))))
person_condition_df_phecode_phenotype$sex_at_birth <- ifelse(person_condition_df_phecode_phenotype$sex_at_birth_concept_id  == 45878463, "Female",
                                                            ifelse(person_condition_df_phecode_phenotype$sex_at_birth_concept_id == 45880669, "Male",
                                                                  ifelse(person_condition_df_phecode_phenotype$sex_at_birth_concept_id == 903096, "NoAnswer",
                                                                        ifelse(person_condition_df_phecode_phenotype$sex_at_birth_concept_id == 0, "NoAnswer",
                                                                              ifelse(person_condition_df_phecode_phenotype$sex_at_birth_concept_id == 46273637, "Intersex",
                                                                                    ifelse(person_condition_df_phecode_phenotype$sex_at_birth_concept_id == 4124462, "None", "NoAnswer"))))))

##############################################################################################
#                                    (Add Age Category)                                      #
##############################################################################################
person_condition_df_phecode_phenotype$age_cat <- ifelse(person_condition_df_phecode_phenotype$age_in_years < 40, 1,
                                                        ifelse(person_condition_df_phecode_phenotype$age_in_years < 70, 2, 3))
person_condition_df_phecode_phenotype$age_cat <- as.factor(person_condition_df_phecode_phenotype$age_cat)

##############################################################################################
#                                    (Add Location)                                          #
##############################################################################################
zip3_wRUCC <-  as.data.table(fread("zip3_wRUCC.csv", header = TRUE))
zip3_wRUCC <- zip3_wRUCC[, -1]
zip3_wRUCC$ZIP3 <- str_pad(zip3_wRUCC$ZIP3, 3, pad = "0")
zip3_wRUCC <- zip3_wRUCC[, c("ZIP3", "wRUCC")]
names(zip3_wRUCC) <- c("zip", "wRUCC")

# Merge AoU data with zip3-to-RUCC key
person_condition_df_phecode_phenotype$zip <- as.factor(person_condition_df_phecode_phenotype$zip)
person_condition_df_phecode_phenotype <- zip3_wRUCC[person_condition_df_phecode_phenotype, on = "zip"]
person_condition_df_phecode_phenotype$location <- ifelse(person_condition_df_phecode_phenotype$wRUCC < 3, "Metro", "NonMetro")
person_table1 <- person_condition_df_phecode_phenotype[, c("person_id", "location", "age_cat", "race_ethnicity", "sex_at_birth")]
person_table1 <- person_table1 %>% distinct()

##############################################################################################
#                                     (Survey Data)                                          #
##############################################################################################
question_id <- c(1585940, 1585386, 903573, 903574, 903575, 903576, 903577, 903578, 1585375, 1585889)
question_id_collapse <- paste0(question_id, collapse = ",")
survey_query <- str_glue("SELECT 
                              answer,
                              question_concept_id,
                              person_id,
                              survey_datetime
                          FROM 
                              `{dataset}.ds_survey` ds_survey 
                          WHERE 
                              ds_survey.question_concept_id IN ({question_id_collapse})")
survey_data <- download_data(survey_query)
survey_data$year <- format(as.Date(survey_data$survey_datetime, format="%d/%m/%Y"),"%Y")

#############
# Education #
#############
# 1585940 What is the highest grade or year of school you completed?
survey_education <- survey_data[which(survey_data$question_concept_id == 1585940), ]
survey_education$education <- ifelse(survey_education$answer %in% c("Highest Grade: Never Attended", "Highest Grade: One Through Four", "Highest Grade: Five Through Eight", "Highest Grade: Nine Through Eleven"), "Eleven or below",
                                    ifelse(survey_education$answer %in% c("Highest Grade: Twelve Or GED", "Highest Grade: College One to Three"), "Twelve or GED", 
                                           ifelse(survey_education$answer %in% c("Highest Grade: College Graduate"), "College Graduate", 
                                                 ifelse(survey_education$answer %in% c("Highest Grade: Advanced Degree"), "Advanced Degree", "NoAnswer"))))
survey_education <- survey_education[, c("person_id", "education")]
survey_education <- as.data.table(survey_education)
survey_education <- survey_education %>% distinct()

##############
# Disability #
##############
# 903573 Are you deaf or do you have serious difficulty hearing?
# 903574 Are you blind or do you have serious difficulty seeing, even when wearing glasses?
# 903575 Because of a physical, mental, or emotional condition, do you have serious difficulty concentrating, remembering or making decisions?
# 903576 Do you have serious difficulty walking or climbing stairs?
# 903577 Do you have difficulty dressing or bathing?
# 903578 Because of a physical, mental, or emotional condition, do you have difficulty doing errands alone such as visiting doctorвЂ™s office or shopping?
survey_disability <- survey_data[which(survey_data$question_concept_id %in% c(903573, 903574, 903575, 903576, 903577, 903578)), ]
survey_disability$disability <- ifelse(survey_disability$answer %in% c("Deaf: Yes", "Blind: Yes", "Errands Alone: Yes",
                                                                       "Dressing Bathing: Yes", "Walking Climbing: Yes", 
                                                                       "Difficulty Concentrating: Yes"), "Yes",
                                      ifelse(survey_disability$answer %in% c("Deaf: No", "Blind: No", "Errands Alone: No",
                                                                       "Dressing Bathing: No", "Walking Climbing: No", 
                                                                       "Difficulty Concentrating: No"), "No", "NoAnswer"))

survey_disability <- survey_disability[, c("person_id", "disability")]
survey_disability <- survey_disability %>% dplyr::group_by(person_id) %>% dplyr::mutate(any_disability = ifelse(any(disability %in% "Yes"), "Yes", disability))
survey_disability <- survey_disability[, c("person_id", "any_disability")]
survey_disability <- as.data.table(survey_disability)
survey_disability <- survey_disability %>% distinct()

##############
#   Income   #
##############
# 1585375 What is your annual household income from all sources?
# 1585889 Not including yourself, how many other people live at home with you?
survey_income <- survey_data[which(survey_data$question_concept_id == 1585375), ]
survey_income <- survey_income[, c("person_id", "answer", "year")]
survey_income$max_income <- ifelse(survey_income$answer %in% c("Annual Income: 10k 25k"), 25000,
                                  ifelse(survey_income$answer %in% c("Annual Income: 25k 35k"), 35000,
                                        ifelse(survey_income$answer %in% c("Annual Income: 35k 50k"), 50000,
                                              ifelse(survey_income$answer %in% c("Annual Income: 50k 75k"), 75000,
                                                    ifelse(survey_income$answer %in% c("Annual Income: 75k 100k"), 100000,
                                                          ifelse(survey_income$answer %in% c("Annual Income: 100k 150k"), 150000,
                                                                ifelse(survey_income$answer %in% c("Annual Income: 150k 200k"), 200000,
                                                                      ifelse(survey_income$answer %in% c("Annual Income: more 200k"), 200001,
                                                                            ifelse(survey_income$answer %in% c("Annual Income: less 10k"), 9999, "NoAnswer")))))))))
survey_income <- survey_income[, c("person_id", "max_income", "year")]
survey_income <- as.data.table(survey_income)

survey_size <- survey_data[which(survey_data$question_concept_id == 1585889), ]
survey_size$family_size <- ifelse(survey_size$answer %in% "0", 1, 
                                  ifelse(survey_size$answer %in% "1", 2, 
                                        ifelse(survey_size$answer %in% "2", 3, 
                                              ifelse(survey_size$answer %in% "3", 4,
                                                    ifelse(survey_size$answer %in% "4", 5,
                                                          ifelse(survey_size$answer %in% "5", 6,
                                                                ifelse(survey_size$answer %in% "6", 7,
                                                                      ifelse(survey_size$answer %in% "7", 8,
                                                                            ifelse(survey_size$answer %in% "8", 9,
                                                                                  ifelse(survey_size$answer %in% "9", 10,
                                                                                        ifelse(survey_size$answer %in% "10", 11, "NoAnswer")))))))))))
survey_size <- survey_size[, c("person_id", "family_size")]
survey_size <- survey_size %>% distinct()
survey_size <- as.data.table(survey_size)
person_id_zip <- person_condition_df_phecode_phenotype[, c("person_id", "zip")]
person_id_zip <- person_id_zip %>% distinct()
survey_size_zip <- person_id_zip[survey_size, on = "person_id"]
survey_size_zip_income <- survey_income[survey_size_zip, on = "person_id"]

income_zip_family_size <- fread("income_zip_long_new.csv", header = TRUE)
income_zip_family_size <- income_zip_family_size[, -1]
income_zip_family_size$zip <- as.character(income_zip_family_size$zip)
income_zip_family_size$year <- as.character(income_zip_family_size$year)

survey_size_zip_income_limit <- income_zip_family_size[survey_size_zip_income, on = c("family_size", "zip", "year")]
survey_size_zip_income_limit <- survey_size_zip_income_limit[-which(survey_size_zip_income_limit$max_income %in% "NoAnswer"), ]
survey_size_zip_income_limit <- survey_size_zip_income_limit[-which(is.na(survey_size_zip_income_limit$zip)), ]
survey_size_zip_income_limit$max_income <- as.double(survey_size_zip_income_limit$max_income)
survey_size_zip_income_limit$low_income <- ifelse(survey_size_zip_income_limit$max_income < survey_size_zip_income_limit$income_limit, "Yes", "No")

survey_low_income <- survey_size_zip_income_limit[, c("person_id", "low_income")]
survey_low_income <- as.data.table(survey_low_income)
survey_low_income <- survey_low_income %>% distinct()

# Merge all data together
person_table1 <- survey_education[person_table1, on = "person_id"]
person_table1 <- survey_disability[person_table1, on = "person_id"]
person_table1 <- survey_low_income[person_table1, on = "person_id"]
person_table1$low_income[which(is.na(person_table1$low_income))] <- "NoAnswer"
person_table1$any_disability[which(is.na(person_table1$any_disability))] <- "NoAnswer"
person_table1$education[which(is.na(person_table1$education))] <- "NoAnswer"

# Merge with number of eligible trials
AoU_to_CTgov_wZip_Trial <- fread("AoU_to_CTgov_wZip_Trial.csv", header = TRUE)
AoU_to_CTgov_wZip_Trial <- AoU_to_CTgov_wZip_Trial[, -1]
person_table1 <- AoU_to_CTgov_wZip_Trial[person_table1, on = "person_id"]

# Create table for PheWAS that contains continuous age instead of categorical age
person_age <- person_condition_df_phecode_phenotype[, c("person_id", "age_in_years")]
person_PheWAS <- person_age[person_table1, on = "person_id"]
person_PheWAS <- person_PheWAS %>% distinct()
person_PheWAS <- person_PheWAS[, c("person_id", "age_in_years", "nMatch", "low_income", "any_disability", "education", "location", "race_ethnicity", "sex_at_birth")]
write.csv(person_PheWAS, file = "person_PheWAS.csv")

Table1_fun <- function(data){
    data_Table1 <- data
    data_Table1_merge <- person_table1[data_Table1, on = "person_id"]
    ageCat1 <- c(mean(data_Table1_merge[which(data_Table1_merge$age_cat == 1),]$nMatch), sd((data_Table1_merge[which(data_Table1_merge$age_cat == 1),]$nMatch)))
    ageCat2 <- c(mean(data_Table1_merge[which(data_Table1_merge$age_cat == 2),]$nMatch), sd((data_Table1_merge[which(data_Table1_merge$age_cat == 2),]$nMatch)))
    ageCat3 <- c(mean(data_Table1_merge[which(data_Table1_merge$age_cat == 3),]$nMatch), sd((data_Table1_merge[which(data_Table1_merge$age_cat == 3),]$nMatch)))
    male <- c(mean(data_Table1_merge[which(data_Table1_merge$sex_at_birth %in% "Male"),]$nMatch), sd((data_Table1_merge[which(data_Table1_merge$sex_at_birth == "Male"),]$nMatch)))
    female <- c(mean(data_Table1_merge[which(data_Table1_merge$sex_at_birth %in% "Female"),]$nMatch), sd((data_Table1_merge[which(data_Table1_merge$sex_at_birth == "Female"),]$nMatch)))
    intersex <- c(mean(data_Table1_merge[which(data_Table1_merge$sex_at_birth %in% "Intersex"),]$nMatch), sd((data_Table1_merge[which(data_Table1_merge$sex_at_birth == "Intersex"),]$nMatch)))
    white <- c(mean(data_Table1_merge[which(data_Table1_merge$race_ethnicity %in% "White"),]$nMatch), sd((data_Table1_merge[which(data_Table1_merge$race_ethnicity == "White"),]$nMatch)))
    black <- c(mean(data_Table1_merge[which(data_Table1_merge$race_ethnicity %in% "Black"),]$nMatch), sd((data_Table1_merge[which(data_Table1_merge$race_ethnicity == "Black"),]$nMatch)))
    hispanic <- c(mean(data_Table1_merge[which(data_Table1_merge$race_ethnicity %in% "Hispanic"),]$nMatch), sd((data_Table1_merge[which(data_Table1_merge$race_ethnicity == "Hispanic"),]$nMatch)))
    asian <- c(mean(data_Table1_merge[which(data_Table1_merge$race_ethnicity %in% "Asian"),]$nMatch), sd((data_Table1_merge[which(data_Table1_merge$race_ethnicity == "Asian"),]$nMatch)))
    mena <- c(mean(data_Table1_merge[which(data_Table1_merge$race_ethnicity %in% "MENA"),]$nMatch), sd((data_Table1_merge[which(data_Table1_merge$race_ethnicity == "MENA"),]$nMatch)))
    nhopi <- c(mean(data_Table1_merge[which(data_Table1_merge$race_ethnicity %in% "NHOPI"),]$nMatch), sd((data_Table1_merge[which(data_Table1_merge$race_ethnicity == "NHOPI"),]$nMatch)))
    multiple <- c(mean(data_Table1_merge[which(data_Table1_merge$race_ethnicity %in% "Multiple"),]$nMatch), sd((data_Table1_merge[which(data_Table1_merge$race_ethnicity == "Multiple"),]$nMatch)))
    other <- c(mean(data_Table1_merge[which(data_Table1_merge$race_ethnicity %in% "Other"),]$nMatch), sd((data_Table1_merge[which(data_Table1_merge$race_ethnicity == "Other"),]$nMatch)))
    metro <- c(mean(data_Table1_merge[which(data_Table1_merge$location %in% "Metro"),]$nMatch), sd((data_Table1_merge[which(data_Table1_merge$location == "Metro"),]$nMatch)))
    nonmetro <- c(mean(data_Table1_merge[which(data_Table1_merge$location %in% "NonMetro"),]$nMatch), sd((data_Table1_merge[which(data_Table1_merge$location == "NonMetro"),]$nMatch)))
    return(data.frame(ageCat1, ageCat2, ageCat3, male, female, intersex, white, black, hispanic, asian, mena, nhopi, multiple, other, metro, nonmetro))
    }

other_Table1 <- Table1_fun(data = AoU_to_CTgov_wZip_Trial_other)
t(other_Table1)

respiratory_Table1 <- Table1_fun(data = AoU_to_CTgov_wZip_Trial_respiratory)
t(respiratory_Table1)

circulatory_Table1 <- Table1_fun(data = AoU_to_CTgov_wZip_Trial_circulatory)
t(circulatory_Table1)

neurological_Table1 <- Table1_fun(data = AoU_to_CTgov_wZip_Trial_neurological)
t(neurological_Table1)

em_Table1 <- Table1_fun(data = AoU_to_CTgov_wZip_Trial_em)
t(em_Table1)

neoplasms_Table1 <- Table1_fun(data = AoU_to_CTgov_wZip_Trial_neoplasms)
t(neoplasms_Table1)

infectious_Table1 <- Table1_fun(data = AoU_to_CTgov_wZip_Trial_infectious)
t(infectious_Table1)
```

```{r, Figure 3}
####################################################################################################
#                                        Figure 3 TOC NIH                                          #
####################################################################################################

counts_wZip_Trial_NIH <- fread("counts_wZip_Trial_NIH.csv", header = TRUE)
counts_wZip_Trial_NIH <- counts_wZip_Trial_NIH[order(counts_wZip_Trial_NIH$n_participant, decreasing = TRUE),]
counts_wZip_Trial_NIH <- counts_wZip_Trial_NIH[1:20, ]
topConditions <- counts_wZip_Trial_NIH$Phecode
counts_wZip_Trial_NIH <- counts_wZip_Trial_NIH[, c("Phenotype", "n_participant", "n_study")]

#############################################################################################################
#                               Quantile Grid Label Plot log2(y + 1) transformation                         #
#############################################################################################################
counts_wZip_Trial_NIH$trans_n_study <- log2(counts_wZip_Trial_NIH$n_study + 2)
participant_min <- min(counts_wZip_Trial_NIH$n_participant)
participant_max <- max(counts_wZip_Trial_NIH$n_participant)
study_min <- min(counts_wZip_Trial_NIH$trans_n_study)
study_max <- max(counts_wZip_Trial_NIH$trans_n_study)

participant_q10 <- quantile(counts_wZip_Trial_NIH$n_participant, .20)
participant_q90 <- quantile(counts_wZip_Trial_NIH$n_participant, .80)
study_q10 <- quantile(counts_wZip_Trial_NIH$trans_n_study, .20)
study_q90 <- quantile(counts_wZip_Trial_NIH$trans_n_study, .80)

vline <- function(x = 0, color = "gray") {
  list(
    type = "line", 
    y0 = 0, 
    y1 = 1, 
    yref = "paper",
    x0 = x, 
    x1 = x, 
    line = list(color = color, dash = "dot")
  )
}

hline <- function(y = 0, color = "gray") {
  list(
    type = "line", 
    x0 = 0, 
    x1 = 1, 
    xref = "paper",
    y0 = y, 
    y1 = y, 
    line = list(color = color, dash = "dot")
  )
}


counts_no_middle <- counts_wZip_Trial_NIH %>% filter((participant_q10 > n_participant) | (n_participant > participant_q90) | (study_q10 > trans_n_study) | (trans_n_study > study_q90)) 

a <- list(
  x = counts_no_middle$n_participant,
  y = counts_no_middle$trans_n_study,
  text = counts_no_middle$Phenotype,
  xref = "x",
  yref = "y",
  #   showarrow = TRUE,
  #   arrowsize = .5,
  #   arrowhead = 2,
  ax = -35,
  ay = -30
)

####################################################################################################
#                                    9-Grid Plots NIH Only Part 3                                  #
####################################################################################################

#############################################################################################################
#                                     Manual Quantile Grid Label Plot                                       #
#############################################################################################################

# counts_no_middle <- counts_wZip_Trial_NIH %>% filter((participant_q10 > n_participant) | (n_participant > participant_q90) | (study_q10 > trans_n_study) | (trans_n_study > study_q90)) 
# counts_middle <- counts_wZip_Trial_NIH %>% filter((n_participant >= participant_q10) & (n_participant <= participant_q90) & (trans_n_study >= study_q10) & (trans_n_study <= study_q90))
quantile_label_counts_plot <- plot_ly(counts_wZip_Trial_NIH, x = ~n_participant, y = ~trans_n_study)
quantile_label_counts_plot <- quantile_label_counts_plot %>% add_markers(x = counts_wZip_Trial_NIH$n_participant,
                                                                         y = counts_wZip_Trial_NIH$trans_n_study,
                                                                         showlegend = F)
# quantile_label_counts_plot <- quantile_label_counts_plot %>% add_markers(x = counts_middle$n_participant,
#                                                                          y = counts_middle$trans_n_study,
#                                                                          marker = list(color = "gray"), showlegend = F)

quantile_label_counts_plot <- quantile_label_counts_plot %>% layout(
  shapes = list(vline(participant_q10), vline(participant_q90),
                hline(study_q10), hline(study_q90),
                # Row 1
                # blue 75, red 25
                list(type = "rect",
                     fillcolor = "#FFC2D4FF",
                     line = list(color = "gray"),
                     opacity = 0.5,
                     y0 = study_q90,
                     y1 = study_max+5,
                     x0 = 0,
                     x1 = participant_q10,
                     layer = "below"),
                # blue 50, red 25
                list(type = "rect",
                     fillcolor = "#BFA7DEFF",
                     line = list(color = "gray"),
                     opacity = 0.5,
                     y0 = study_q90,
                     y1 = study_max+5,
                     x0 = participant_q10,
                     x1 = participant_q90,
                     layer = "below"),
                # blue 25, red 25
                list(type = "rect",
                     fillcolor = "#BD8DDAFF",
                     line = list(color = "gray"),
                     opacity = 0.5,
                     y0 = study_q90,
                     y1 = study_max+5,
                     x0 = participant_q90,
                     x1 = participant_max+5000,
                     layer = "below"),
                # Row 2
                # blue 75, red 50
                list(type = "rect",
                     fillcolor = "#FFDAE0FF",
                     line = list(color = "gray"),
                     opacity = 0.5,
                     y0 = study_q10,
                     y1 = study_q90,
                     x0 = 0,
                     x1 = participant_q10,
                     layer = "below"),
                # blue 50, red 50
                list(type = "rect",
                     fillcolor = "#CCBAE1FF",
                     line = list(color = "gray"),
                     opacity = 0.5,
                     y0 = study_q10,
                     y1 = study_q90,
                     x0 = participant_q10,
                     x1 = participant_q90,
                     layer = "below"),
                # blue 25, red 50
                list(type = "rect",
                     fillcolor = "#C7A2DBFF",
                     line = list(color = "gray"),
                     opacity = 0.5,
                     y0 = study_q10,
                     y1 = study_q90,
                     x0 = participant_q90,
                     x1 = participant_max+5000,
                     layer = "below"),
                # Row 3
                # blue 75, red 75
                list(type = "rect",
                     fillcolor = "white",
                     line = list(color = "gray"),
                     opacity = 0.5,
                     y0 = 0,
                     y1 = study_q10,
                     x0 = 0,
                     x1 = participant_q10,
                     layer = "below"),
                # blue 50, red 75
                list(type = "rect",
                     fillcolor = "#C3DFF7FF",
                     line = list(color = "gray"),
                     opacity = 0.5,
                     y0 = 0,
                     y1 = study_q10,
                     x0 = participant_q10,
                     x1 = participant_q90,
                     layer = "below"),
                # blue 25, red 75
                list(type = "rect",
                     fillcolor = "#B7C9F7FF",
                     line = list(color = "gray"),
                     opacity = 0.5,
                     y0 = 0,
                     y1 = study_q10,
                     x0 = participant_q90,
                     x1 = participant_max+5000,
                     layer = "below")),
  xaxis = list(range=c(participant_min-5000,participant_max+5000)),
  yaxis = list(range=c(0,study_max+1)))


text_right_concept <- c("Other headache syndromes", "Osteoarthrosis, localized, primary", "Anxiety disorder", "Shortness of breath", "GERD")
text_top_concept <- c("Pain in joint", "Hyperlipidemia", "Abdominal pain",
                      "Depression", "Obesity",
                      "Chronic pain", "Vitamin D deficiency", "Other anemias", "Cough") 
text_left_concept <- c("Type 2 diabetes", "Essential hypertension", "Back pain", "Pain in limb", "Nonspecific chest pain")
text_bottom_concept <- c("Malaise and fatigue", "Tobacco use disorder", "Major depressive disorder")
text_right_dat <- counts_wZip_Trial_NIH[which(counts_wZip_Trial_NIH$Phenotype %in% text_right_concept), ]
text_left_dat <- counts_wZip_Trial_NIH[which(counts_wZip_Trial_NIH$Phenotype %in% text_left_concept), ]
text_top_dat <- counts_wZip_Trial_NIH[which(counts_wZip_Trial_NIH$Phenotype %in% text_top_concept), ]
text_bottom_dat <- counts_wZip_Trial_NIH[which(counts_wZip_Trial_NIH$Phenotype %in% text_bottom_concept), ]

text_right <- list(
  x = text_right_dat$n_participant,
  y = text_right_dat$trans_n_study,
  text = text_right_dat$Phenotype,
  xref = "x",
  yref = "y",
  showarrow = FALSE,
  xanchor = "left"
)

text_top <- list(
  x = text_top_dat$n_participant,
  y = text_top_dat$trans_n_study,
  text = text_top_dat$Phenotype,
  xref = "x",
  yref = "y",
  showarrow = FALSE,
  yanchor = "bottom"
)

text_left <- list(
  x = text_left_dat$n_participant,
  y = text_left_dat$trans_n_study,
  text = text_left_dat$Phenotype,
  xref = "x",
  yref = "y",
  showarrow = FALSE,
  xanchor = "right"
)

text_bottom <- list(
  x = text_bottom_dat$n_participant,
  y = text_bottom_dat$trans_n_study,
  text = text_bottom_dat$Phenotype,
  xref = "x",
  yref = "y",
  showarrow = FALSE,
  yanchor = "top"
)

quantile_label_counts_plot <- quantile_label_counts_plot %>% layout(annotations = text_right)
quantile_label_counts_plot <- quantile_label_counts_plot %>% layout(annotations = text_left)
quantile_label_counts_plot <- quantile_label_counts_plot %>% layout(annotations = text_top)
quantile_label_counts_plot <- quantile_label_counts_plot %>% layout(annotations = text_bottom)
quantile_label_counts_plot <- quantile_label_counts_plot %>% layout(xaxis = list(title = "Number of Participants"),
                                                                    yaxis = list(title = "Number of Matched Trials"),
                                                                    font = list(size = 15))
y_labels <- 2^(1:10)-2
quantile_label_counts_plot <- quantile_label_counts_plot %>% layout(yaxis = list(
  ticktext = y_labels,
  tickvals = 1:10,
  range = c(-1, 10),
  xaxis = list(range = c(0, 90000))
))
quantile_label_counts_plot %>% layout(annotations = list(text = "Many Participants \n Many Trials",  x = (80000 - participant_q90)/2 + participant_q90, y = (10 - study_q90)/2 + study_q90, font = list(
  color = "gray",
  size = 17
), opacity = 0.2, showarrow = FALSE)) %>% layout(annotations = list(text = "Many Participants \n Some Trials",  x = (80000 - participant_q90)/2 + participant_q90, y = (study_q90 - study_q10)/2 + study_q10, font = list(
  color = "gray",
  size = 17
), opacity = 0.2, showarrow = FALSE)) %>% layout(annotations = list(text = "Many Participants \n Few Trials",  x = (80000 - participant_q90)/2 + participant_q90, y = (study_q10 - study_min)/4 + study_min, font = list(
  color = "gray",
  size = 17
), opacity = 0.2, showarrow = FALSE)) %>% layout(annotations = list(text = "Some Participants \n Few Trials",  x = (participant_q90 - participant_q10)/2 + participant_q10, y = (study_q10 - study_min)/4 + study_min, font = list(
  color = "gray",
  size = 17
), opacity = 0.2, showarrow = FALSE)) %>% layout(annotations = list(text = "Some Participants \n Some Trials",  x = (participant_q90 - participant_q10)/2 + participant_q10, y = (study_q90 - study_q10)/2 + study_q10, font = list(
  color = "gray",
  size = 17
), opacity = 0.2, showarrow = FALSE)) %>% layout(annotations = list(text = "Some Participants \n Many Trials",  x = (participant_q90 - participant_q10)/2 + participant_q10, y = (10 - study_q90)/2 + study_q90, font = list(
  color = "gray",
  size = 17
), opacity = 0.2, showarrow = FALSE)) %>% layout(annotations = list(text = "Few Participants \n Many Trials",  x = participant_min - 500, y = (10 - study_q90)/2 + study_q90, font = list(
  color = "gray",
  size = 17
), opacity = 0.2, showarrow = FALSE)) %>% layout(annotations = list(text = "Few Participants \n Some Trials",  x = participant_min - 500, y = (study_q90 - study_q10)/2 + study_q10, font = list(
  color = "gray",
  size = 17
), opacity = 0.2, showarrow = FALSE)) %>% layout(annotations = list(text = "Few Participants \n Few Trials",  x = participant_min - 500, y = (study_q10 - study_min)/4 + study_min, font = list(
  color = "gray",
  size = 17
), opacity = 0.2, showarrow = FALSE))
```

```{r, PheWAS Helper Functions for Figure 4}
##############################################################################################
#                                  PheWAS Helper Functions                                   #
#                                                                                            #
##############################################################################################
###########################################################################################################
# data_fun : Prepares dataset for PheWAS
# 
# Input: 
# data - dataset with person_id, age, sex, Phecode, zip
# 
# Output:
# dataset with person_id, age, sex, Phecode, location, R/E, education level, income level, disability status, n_condition, nMatch
#
###########################################################################################################
data_fun <- function(data){
  #######################################################################################################
  #                      tab1: person_id, nMatch (match on condition, age, and sex)                     #
  #######################################################################################################
  tab1 <- fread("person_PheWAS.csv", header = TRUE)
  tab1 <- tab1[, -1]

  #######################################################################################################
  #                                 tab2: person_id, Phecode                                            #
  #######################################################################################################
  tab2 <- as.data.table(data[, c("person_id", "Phecode")]) %>% distinct()
  # tab2 <- as.data.table(person_condition %>% group_by(person_id) %>% summarise(n_condition = n_distinct(Phecode)))

  #######################################################################################################
  #                     tab1_tab2: person_id, nMatch, age, sex, location                                # 
  #                                R/E, education level, income level, disability status                #
  #######################################################################################################
  tab1_tab2 <- tab1[tab2, on = "person_id"]
  tab1_tab2$low_income <- as.factor(tab1_tab2$low_income)
  tab1_tab2$any_disability <- as.factor(tab1_tab2$any_disability)
  tab1_tab2$education <- as.factor(tab1_tab2$education)
  tab1_tab2$location <- as.factor(tab1_tab2$location)
  tab1_tab2$race_ethnicity <- as.factor(tab1_tab2$race_ethnicity)
  tab1_tab2$sex_at_birth <- as.factor(tab1_tab2$sex_at_birth)
  return(tab1_tab2)
}


###########################################################################################################
# nb_fun : Performs negative-binomial regression nMatch ~ age + sex + Phecode_indicator + location + R/E + disability + income + education
# 
# Input: 
# data - dataset with person_id, n_condition, nMatch, age, sex, Phecode, location
# Phecode_cur - Phecode of interest
# 
# Output:
# model summary of condition_indicator (effect size, SE, p-value)
#
###########################################################################################################
nb_fun <- function(data, Phecode_cur){
  dat <- data %>% group_by(person_id) %>% mutate(Phecode_indicator = as.factor(as.integer(any(Phecode %in% Phecode_cur))))
  dat <- dat %>% dplyr::select(person_id, sex_at_birth, age_in_years, nMatch, Phecode_indicator, location, race_ethnicity, education, low_income, any_disability) %>% distinct()
  mod <- glm.nb(nMatch ~ relevel(Phecode_indicator, ref = "0") + sex_at_birth + age_in_years + location + race_ethnicity + education + low_income + any_disability, data = dat)
  summary(mod)$coefficients[2, ]
}

###########################################################################################################
# Manhattan plot helper functions
###########################################################################################################
phewasManhattan_mod <- function (d, annotate.phenotype.description = T, ...) 
{
  if (sum(c("phenotype", "p") %in% names(d)) < 2) 
    stop("Data input must contain columns phenotype and p.")
  if (class(d$phenotype) != "character") {
    if (class(d$phenotype) == "factor") {
      warning("Factor phenotype input mapped to characters")
      d$phenotype = as.character(d$phenotype)
    }
    else {
      stop("Non-character or non-factor phenotypes passed in, so an accurate phecode mapping is not possible.")
    }
  }
  if (min(nchar(d$phenotype)) < 3) 
    warning("Phenotypes with length <3 observed, ensure they are are 0-padded (e.g., \"008\")")
  d = addPhecodeInfo(d, groupnums = T, groupcolors = T)
  phenotypeManhattan_mod(d, annotate.phenotype.description = annotate.phenotype.description, 
                         ...)
}


phenotypeManhattan_mod <- function (d, suggestive.line = 0.05, significant.line, OR.size = F, 
                                    OR.direction = F, sizes, annotate.level, y.axis.interval = 5, 
                                    y.axis.label = expression(-log[10](italic(p))), max.y, ...) 
{
  if (sum(c("phenotype", "p") %in% names(d)) < 2) 
    stop("Data input must contain columns phenotype and p.")
  if ((OR.size | OR.direction) & !length(d$OR)) 
    stop("OR size or direction requested, but d$OR not provided.")
  if (OR.size & !is.null(list(...)$sizes)) 
    stop("You cannot use OR.size=T for OR point sizes and use the second point sizing parameter 'sizes'.")
  if (OR.direction & !is.null(list(...)$direction)) 
    stop("You cannot use OR.direction=T for OR direction shapes and use the second point shape parameter 'direction'.")
  if (max(names(list(...)) %in% c("genomewide.line", "sort.by.p", 
                                  "sort.by.category.p")) > 0) {
    stop("'genomewide.line','sort.by.p', and 'sort.by.category.p' parameters have been replaced with 'significant.line','sort.by.value', and 'sort.by.category.value'")
  }
  d = d[!is.na(d$p), ]
  if (missing(significant.line)) 
    significant.line = suggestive.line/nrow(d)
  significant.line = -log10(significant.line)
  suggestive.line = -log10(suggestive.line)
  if (missing(annotate.level)) {
    if (is.na(significant.line)) {
      annotate.level = -log10(min(d$p, na.rm = T))
    }
    else {
      annotate.level = significant.line
    }
  }
  else {
    annotate.level = -log10(annotate.level)
  }
  if (sum(d$p == 0) > 0) 
    d[d$p == 0, ]$p = .Machine$double.xmin
  d = d[d$p > 0 & d$p <= 1, ]
  d$value = -log10(d$p)
  max.y = ifelse(missing(max.y), max(ceiling(max(d$value)), 
                                     4.4), max.y)
  sizing = FALSE
  if (!missing(sizes)) {
    if (sizes == T) {
      if (OR.size) {
        stop("Both sizes and OR.size are TRUE. Only one size can be used at a time. Please ensure only one parameter is TRUE.")
      }
      if (!length(d$size)) {
        stop("sizes were requested, but no d$size was not provided. Please provide the point size scaling variable in d$size")
      }
      sizing = TRUE
    }
  }
  if (OR.size) {
    sizing = TRUE
    d$size = d$OR
    d[d$size < 1, ]$size = 1/d[d$size < 1, ]$size
  }
  if (OR.direction) 
    d$direction = d$OR >= 1
  plot = phenotypePlot_mod(d, suggestive.line = suggestive.line, 
                           significant.line = significant.line, sizes = sizing, 
                           direction = OR.direction, annotate.level = annotate.level, 
                           y.axis.interval = y.axis.interval, y.axis.label = y.axis.label, 
                           max.y = max.y, ...)
  if (OR.size) 
    plot = suppressMessages(plot + scale_size("Odds Ratio", 
                                              range = c(2, 5), breaks = wavier(), n.breaks = 3))
  plot
}


phenotypePlot_mod <- function (d, max.y, max.x, suggestive.line, significant.line, 
                               size.x.labels = 9, size.y.labels = 9, switch.axis = F, sort.by.value = F, 
                               sort.by.category.value = F, base.labels = F, annotate.phenotype.description, 
                               annotate.angle = 0, annotate.size = 5, annotate.level, annotate.phenotype = F, 
                               annotate.snp.w.phenotype = F, annotate.snp = F, annotate.snp.angle = 0, 
                               annotate.list, annotate.only.largest = T, lc.labels = F, 
                               x.group.labels = T, x.phenotype.labels = F, sizes = F, direction = F, 
                               point.size = 3, use.color = T, color.palette, title = paste0("Phenotype Plot ", 
                                                                                            date()), x.axis.label = "Phenotypes", y.axis.label = "Values", 
                               y.axis.interval = 5) 
{
  if (sum(c("phenotype", "value") %in% names(d)) < 2) 
    stop("Data input must contain columns phenotype and value.")
  if (!missing(annotate.phenotype.description)) {
    if (is.data.frame(annotate.phenotype.description) && 
        sum(c("phenotype", "description") %in% names(annotate.phenotype.description)) == 
        2) {
      d = merge(d, annotate.phenotype.description)
      annotate.phenotype.description = T
    }
    else if (is.logical(annotate.phenotype.description)) {
      if (annotate.phenotype.description == T && !length(d$description)) {
        stop("Annotate.phenotype.description must contain columns phenotype and description, or be TRUE with provided d$description.")
      }
    }
    else {
      stop("Annotate.phenotype.description must contain columns phenotype and description, or be TRUE with provided d$description.")
    }
  }
  else {
    annotate.phenotype.description = F
  }
  if ((annotate.snp || annotate.snp.w.phenotype) && !("snp" %in% 
                                                      names(d))) 
    stop("You requested SNP annotation but d$snp is not defined.")
  if (annotate.snp.w.phenotype && annotate.snp) 
    warning("You requested SNP annotation twice")
  annotate = annotate.phenotype.description || annotate.phenotype || 
    annotate.snp || annotate.snp.w.phenotype
  if (annotate && (missing(annotate.level) || is.na(annotate.level)) && 
      missing(annotate.list)) {
    warning("You requested annotation, but did not specify annotate.level or annotate.list.")
    annotate = F
  }
  if (!use.color && !missing(color.palette)) 
    stop("You requested no color, but provided a color palette.")
  if (use.color) {
    if (missing(color.palette)) {
      if (!("color" %in% names(d))) 
        stop("You requested color, but did not provide a color attribute in d or color.palette")
      else if (class(d$color) == "factor") 
        warning("The color attribute is a factor and no color palette is provided: R default color scheme will be used. Convert color to character if it contains color names or codes")
    }
    if (!missing(color.palette) && !length(d$color)) {
      if (length(d$groupnum)) 
        d$color = d$groupnum
      else stop("You requested use.color, but d$color or d$groupnum were not provided to distinguish groups.")
    }
  }
  else {
    d$color = "#000000"
  }
  if (sizes && !length(d$size)) 
    stop("You requested size information, but did not provide d$size")
  if (direction && !length(d$direction)) 
    stop("You requested direction information, but did not provide d$direction")
  if (!sizes) 
    d$size = point.size
  if (!annotate.phenotype.description && !annotate.phenotype && 
      !annotate.snp && !annotate.snp.w.phenotype) 
    lc.labels = F
  if (sort.by.value && x.group.labels) 
    stop("One cannot sort universally by value and have x group labels. Try sort.by.category.value or not labeling the groups.")
  if ((sort.by.category.value || x.group.labels) && (sum(c("groupnum", 
                                                           "group") %in% names(d)) < 2)) {
    stop("Requested group information, but did not provide d$groupnum and d$group.")
  }
  if (!("groupnum" %in% names(d))) {
    d$groupnum = 0
  }
  d = d[!(is.na(d$phenotype) | is.na(d$value)), ]
  d = d[order(d$phenotype), ]
  if (missing(max.x)) 
    max.x = length(unique(d$phenotype))
  phenotypes = aggregate(value ~ phenotype + groupnum, d, FUN = max)
  phenotypes = phenotypes[order(phenotypes$value, decreasing = T), 
  ][1:min(nrow(phenotypes), max.x), ]
  if (sort.by.value) {
    phenotypes = phenotypes[order(phenotypes$value, decreasing = T), 
    ]
  }
  else if (sort.by.category.value) {
    phenotypes = phenotypes[order(-phenotypes$groupnum, phenotypes$value, 
                                  decreasing = T), ]
  }
  else {
    phenotypes = phenotypes[order(phenotypes$groupnum, phenotypes$phenotype), 
    ]
  }
  phenotypes$seq = 1:nrow(phenotypes)
  phenotypes = phenotypes[, c("phenotype", "seq", "value")]
  names(phenotypes)[3] = "min.value"
  d = inner_join(phenotypes, d, by = "phenotype")
  d = d[order(d$seq), ]
  if (missing(max.y)) 
    max.y = ceiling(max(d$value))
  if (switch.axis) {
    d = d[nrow(d):1, ]
    d$groupnum = max(d$groupnum) - d$groupnum + 1
    d$seq = max(d$seq) - d$seq + 1
  }
  if (x.group.labels) {
    labels = dplyr::summarize(group_by(d, groupnum), tick = mean(unique(seq)), 
                       label = as.character(group[1]))
    labels = labels[order(labels$tick), ]
  }
  if (missing(color.palette)) {
    color.palette = unique(d[order(d$seq), ]$color)
    names(color.palette) = color.palette
  }
  else {
    names(color.palette) = unique(d[order(d$seq), ]$color)
  }
  if (!switch.axis) {
    plot = ggplot(d, ylab = y.axis.label, xlab = x.axis.label)
    if (!missing(suggestive.line) && !is.na(suggestive.line)) 
      plot = plot + geom_hline(yintercept = suggestive.line, 
                               colour = "blue", alpha = I(1/3), size = 1)
    if (!missing(significant.line) && !is.na(significant.line)) 
      plot = plot + geom_hline(yintercept = significant.line, 
                               colour = "red", alpha = I(1/3), size = 1)
    plot = plot + aes(seq, value, size = size, colour = color)
    if (!sizes) 
      plot = plot + scale_size(range = c(point.size, point.size), 
                               guide = "none")
    plot = plot + geom_point()
    plot = plot + scale_colour_manual(values = color.palette, 
                                      guide = "none")
    if (x.group.labels) {
      plot = plot + scale_x_continuous(name = x.axis.label, 
                                       limits = c(1, max.x), breaks = labels$tick, labels = labels$label, 
                                       expand = c(0.01, 0))
    }
    else {
      plot = plot + scale_x_continuous(name = x.axis.label, 
                                       limits = c(1, max.x), breaks = c(-100), labels = c(""), 
                                       expand = c(0.015, 0))
    }
    plot = plot + scale_y_continuous(y.axis.label, limits = c(0, 
                                                              max.y), breaks = seq(0, max.y, y.axis.interval), 
                                     expand = c(0, 0.2))
    plot = plot + theme(panel.background = element_blank(), 
                        panel.grid.minor = element_blank(), axis.text.x = element_text(size = size.x.labels, 
                                                                                       colour = "black", angle = 50, hjust = 1, vjust = 1), 
                        axis.text.y = element_text(size = size.y.labels, 
                                                   colour = "black"), axis.line = element_line(colour = "black"), 
                        axis.ticks = element_line(colour = "black"))
  }
  else {
    plot = ggplot(d, xlab = y.axis.label, ylab = x.axis.label)
    if (!missing(suggestive.line) && !is.na(suggestive.line)) 
      plot = plot + geom_vline(xintercept = suggestive.line, 
                               colour = "blue", alpha = I(1/3), size = 1)
    if (!missing(significant.line) && !is.na(significant.line)) 
      plot = plot + geom_vline(xintercept = significant.line, 
                               colour = "red", alpha = I(1/3), size = 1)
    plot = plot + aes(value, seq, size = size, colour = color)
    if (!sizes) 
      plot = plot + scale_size(range = c(point.size, point.size), 
                               guide = "none")
    plot = plot + geom_point()
    plot = plot + scale_colour_manual(values = color.palette, 
                                      guide = "none")
    if (x.group.labels) {
      plot = plot + scale_y_continuous(name = x.axis.label, 
                                       limits = c(1, max.x), breaks = labels$tick, labels = labels$label, 
                                       expand = c(0.015, 0.02))
    }
    else {
      plot = plot + scale_y_continuous(name = x.axis.label, 
                                       limits = c(0, max.x), breaks = c(-100), labels = c(""), 
                                       expand = c(0.015, 0))
    }
    plot = plot + scale_x_continuous(y.axis.label, limits = c(0, 
                                                              max.y), breaks = seq(0, max.y, y.axis.interval), 
                                     expand = c(0, 0.2))
    plot = plot + theme(panel.background = element_blank(), 
                        panel.grid.minor = element_blank(), axis.text.y = element_text(size = size.x.labels, 
                                                                                       colour = "black", hjust = 1, vjust = 0.5), axis.text.x = element_text(size = size.y.labels, 
                                                                                                                                                             colour = "black", hjust = 0.5, vjust = 0), axis.line = element_line(colour = "black"), 
                        axis.ticks = element_line(colour = "black"))
  }
  plot = plot + theme(legend.position = "none")
  if (sizes) {
    plot = suppressWarnings(plot + theme(legend.position = "right") + 
                              scale_size("Size", range = c(point.size, 2 * point.size)))
  }
  if (direction) {
    plot = plot + aes(shape = factor(direction), fill = color) + 
      scale_shape("Direction", solid = TRUE) + scale_shape_manual(values = c(25, 
                                                                             24)) + scale_fill_manual(values = color.palette, 
                                                                                                      guide = "none")
  }
  if (annotate) {
    d$annotate = F
    if (!missing(annotate.list)) 
      d[d$phenotype %in% annotate.list, ]$annotate = T
    if ((!missing(annotate.level) && !is.na(annotate.level)) && 
        (sum(d$value >= annotate.level) > 0)) 
      d[d$value >= annotate.level, ]$annotate = T
    if (sum(d$value != d$min.value) > 0 && annotate.only.largest) 
      d[d$value != d$min.value, ]$annotate = F
    if (!annotate.phenotype.description) {
      d$description = ""
    }
    if (annotate.phenotype) 
      d$description = paste(d$phenotype, ifelse(d$description == 
                                                  "", "", paste(":", d$description)), sep = "")
    if (annotate.snp.w.phenotype) 
      d$description = paste(d$snp, ifelse(d$description == 
                                            "", "", paste(":", d$description)), sep = "")
    d$description = substr(d$description, 1, 60)
    d$description = paste0("  ", d$description)
    if (lc.labels) 
      d$description = tolower(d$description)
    if (sum(d$annotate) == 0) {
      warning("Annotation requested, but no points met criteria")
    }
    else {
      if (annotate.phenotype.description || annotate.phenotype || 
          annotate.snp.w.phenotype) {
        plot = plot + if (!base.labels) {
          ggrepel::geom_text_repel(aes(label = description), 
                                   colour = "black", data = d[d$annotate, ], 
                                   size = annotate.size, angle = annotate.angle, max.overlaps = 15)
        }
        else {
          geom_text(aes(label = description), colour = "black", 
                    data = d[d$annotate, ], hjust = 0, size = annotate.size, 
                    angle = annotate.angle)
        }
      }
      if (annotate.snp) {
        plot = plot + if (!base.labels) {
          ggrepel::geom_text_repel(aes(label = snp), 
                                   colour = "black", data = d[d$annotate, ], 
                                   size = annotate.size, angle = annotate.snp.angle, max.overlaps = 15)
        }
        else {
          geom_text(aes(label = snp), colour = "black", 
                    data = d[d$annotate, ], hjust = 0, size = annotate.size, 
                    angle = annotate.snp.angle)
        }
      }
    }
  }
  plot = plot + labs(title = title) + theme(title = element_text(size = 12))
  plot = plot + geom_hline(yintercept = significant.line,
                           colour = "red", alpha = 0.5, size = 1)
  plot 
}
```

```{r}
##############################################################################################
#                                (All Participants)                                          #
##############################################################################################

##############################################################################################
#                                     Read in Data                                           #
##############################################################################################
# AoU data
person_condition_df_phecode_phenotype <- as.data.table(fread("person_condition_df_phecode_phenotype.csv", header = TRUE))
person_condition_df_phecode_phenotype <- person_condition_df_phecode_phenotype[, c("person_id", "sex_at_birth_concept_id", "age_in_years", "PheCode", "value_as_string")]
names(person_condition_df_phecode_phenotype) <- c("person_id", "sex_at_birth_concept_id", "age_in_years", "Phecode", "value_as_string")

person_condition_df_phecode_phenotype$zip <- sub("^.*([0-9]{3}).*", "\\1", person_condition_df_phecode_phenotype$value_as_string)
# Remove rows with invalid zip (000)
person_condition_df_phecode_phenotype <- person_condition_df_phecode_phenotype[-which(person_condition_df_phecode_phenotype$zip %in% "000"), ]
person_condition_df_phecode_phenotype <- person_condition_df_phecode_phenotype[, c("person_id", "sex_at_birth_concept_id", "age_in_years", "Phecode", "zip")]
# Code sex as male, female, or other to match with CTgov 
person_condition_df_phecode_phenotype$sex_at_birth_concept_id[which(!(person_condition_df_phecode_phenotype$sex_at_birth_concept_id %in% c(45880669, 45878463)))] <- 9999999999
person_condition_df_phecode_phenotype$zip <- as.factor(person_condition_df_phecode_phenotype$zip)

tab1_tab2_tab3 <- data_fun(person_condition_df_phecode_phenotype)
unique_Phecode <- unique(person_condition_df_phecode_phenotype$Phecode)
cores <- detectCores()
cl <- makeCluster(8)
registerDoParallel(cl)

nb_out <- foreach(i = 1:length(unique_Phecode), .combine = rbind, .packages = c("dplyr", "MASS")) %dopar% {
    temp <- nb_fun(data = tab1_tab2_tab3, Phecode_cur = unique_Phecode[i])
    temp_df <- as.data.frame(t(temp))
    temp_df$Phecode <- unique_Phecode[i]
    temp_df
}
stopCluster(cl)
# write.csv(nb_out, file = "Trial_Eligibility_PheWAS_20230623.csv")

Trial_Eligibility_PheWAS <- as.data.table(fread("Trial_Eligibility_PheWAS_20230623.csv", header = TRUE))

# Bonferroni adjustment
numTest <- nrow(Trial_Eligibility_PheWAS)
corrected_p <- 0.05/numTest
Trial_Eligibility_PheWAS <- as.data.table(fread("Trial_Eligibility_PheWAS_20230623.csv", header = TRUE))
Trial_Eligibility_PheWAS <- Trial_Eligibility_PheWAS[, -1]
Trial_Eligibility_PheWAS$OR <- exp(Trial_Eligibility_PheWAS$Estimate)
# The first column is not really the OR but the RR (labeling it as OR makes it compatible with PheWAS package)
names(Trial_Eligibility_PheWAS) <- c("Estimate", "SE", "z", "p", "phenotype", "OR")

Trial_Eligibility_PheWAS$phenotype <- as.character(Trial_Eligibility_PheWAS$phenotype)
Trial_Eligibility_PheWAS[which(nchar(Trial_Eligibility_PheWAS$phenotype) < 3), ]$phenotype <- str_pad(Trial_Eligibility_PheWAS[which(nchar(Trial_Eligibility_PheWAS$phenotype) < 3), ]$phenotype, 3, pad = "0")
#jpeg("AoU_PheWAS_Overall_Top20_New.jpeg", units = "in", width = 10, height = 8, res = 300)
phewasManhattan_mod(Trial_Eligibility_PheWAS[, c("phenotype", "p", "OR")], 
                    title = "", 
                    significant.line = corrected_p, suggestive.line = corrected_p, y.axis.interval = 100,
                    annotate.size = 3.5, OR.direction = FALSE, OR.size = FALSE, point.size = 3, max.y = 330,
                    annotate.level = 9e-98)
#dev.off()
View(Trial_Eligibility_PheWAS[order(Trial_Eligibility_PheWAS$p), ])
check_Overall <- addPhecodeInfo(Trial_Eligibility_PheWAS[which(Trial_Eligibility_PheWAS$p < corrected_p), ]); nrow(check_Overall)
check_Overall <- check_Overall[order(check_Overall$OR, decreasing = TRUE), ]
check_Overall$description <- factor(check_Overall$description, levels = check_Overall$description)
check_Overall$lower <- exp(check_Overall$Estimate - 1.96 * check_Overall$SE)
check_Overall$upper <- exp(check_Overall$Estimate + 1.96 * check_Overall$SE)
View(check_Overall[order(check_Overall$p), ])
top20 <- check_Overall[order(check_Overall$p), ]
top20 <- top20[1:20, ]
View(top20[order(top20$OR, decreasing = TRUE), ])
```
